### ISSUE TITLE
Die Verbindung klappt noch nicht ganz...

### ISSUE THREAD

**Issue by redneptun** [majuss/easybox904#1]
Hallo!
Danke erstmal für dieses schöne Tutorial! Ich komme per SSH auf meine Box, Provider-Benutzername und -Passwort sind gesetzt und in der Übersicht wird mir meine verfügbare Bandbreite angezeigt, allerdings wird keine Verbindung aufgebaut und der Router erhält keine WAN-IP.
Hier ein paar Screens:
![bildschirmfoto_2017-03-21_23-38-45](https://cloud.githubusercontent.com/assets/3009878/24174175/9b5ce3c0-0e8f-11e7-818c-1b3ba2a7831c.png)
![bildschirmfoto_2017-03-21_23-36-37](https://cloud.githubusercontent.com/assets/3009878/24174176/9b60f82a-0e8f-11e7-8d11-c200f7b981d5.png)
Hast du vielleicht einen Rat für mich? PS: Mein Anbieter ist WOBCOM.
Vielen Dank schonmal!
LG

**Comment by majuss** [comment]
Hey!

dann einfach noch einmal `/usr/sbin/ccfg_cli`bemühen. Am besten die Übersicht aller Werte printen lassen. Vlt. auch noch WAN002 etc. eintragen. Oder andere Werte stimmen nicht. Geht der Anschluss mit einem anderen Router? 

Du kannst deinen Provider mal nach einer ausführlichen Konfigurationsanleitung fragen.

In welchem Format ist denn dein Benutzername und Passwort? Sonderzeichen (space etc.) drin?

**Comment by shownb** [comment]
Hallo majuss,
ich brauche deine Hilfe auch.Mein Gerät ist easybox-804.Wenn ich die 804.bin binwalk, zeigt es mir so.

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
15265         0x3BA1          xz compressed data
16045         0x3EAD          xz compressed data
5963041       0x5AFD21        xz compressed data
5988354       0x5B6002        xz compressed data
6040234       0x5C2AAA        xz compressed data
6083367       0x5CD327        xz compressed data
6120432       0x5D63F0        xz compressed data
6155964       0x5DEEBC        xz compressed data
...
...
7562061       0x73634D        Squashfs filesystem

und ich unsquashfs die Squashfs filesystem.Es gibt nür wenig file.

root@esp8266:~/easybox/extracted/squashfs-root/etc# ls -la
total 140
drwxrwxrwx 6 root root  4096 Nov  3 12:37 .
drwxrwxrwx 7 root root  4096 Nov  3 12:37 ..
-rw-rw-rw- 1 root root 14336 Dec  4  2014 14011027.bin
-rw-rw-rw- 1 root root 13523 Sep  4  2014 activation_wizard.conf
-rw-rw-rw- 1 root root  2435 Nov 12  2014 activation_wizard_dsl.conf
drwxrwxrwx 2 root root  4096 Nov  3 12:37 asterisk
-rw-rw-rw- 1 root root    59 Jul 22  2015 ematch_map
-rw-rw-rw- 1 root root    31 Jul 22  2015 group
-rw-rw-rw- 1 root root     1 Apr 26  2005 hosts
-rw-rw-rw- 1 root root   181 Jan 26  2011 key.pub
-rw-rw-rw- 1 root root  1050 Feb 21  2001 nsswitch.conf
-rw-rw-rw- 1 root root   823 Aug 16  2012 pktloc
-rw-rw-rw- 1 root root  1186 Feb 21  2001 protocols
-rw-rw-rw- 1 root root    21 May 22  2002 resolv.conf
-rw-rw-rw- 1 root root   442 Jul 22  2015 rt_dsfield
-rw-rw-rw- 1 root root   317 Jul 22  2015 rt_protos
-rw-rw-rw- 1 root root   112 Jul 22  2015 rt_realms
-rw-rw-rw- 1 root root    92 Jul 22  2015 rt_scopes
-rw-rw-rw- 1 root root    87 Jul 22  2015 rt_tables
-rw-rw-rw- 1 root root 11194 Jan 19  2005 services
drwxrwxrwx 2 root root  4096 Nov  3 12:37 ssh
drwxrwxrwx 2 root root  4096 Nov  3 12:37 telephonyProfiles.d
-rw-rw-rw- 1 root root  1324 Sep  1  2014 user_fw_update.conf
-rw-rw-rw- 1 root root  1481 Mar 31  2015 vf_vox2_5_de_hg_api_config.json
-rw-rw-rw- 1 root root  2490 Sep 11  2015 vf_vox2_5_it_hg_api_config.json
-rw-rw-rw- 1 root root   818 Aug  5  2015 vf_vox2_5_uk_hg_api_config.json
drwxrwxrwx 2 root root  4096 Nov  3 12:37 wlan


Was solle ich machen?

**Comment by majuss** [comment]
Hey,

I have a look at it! What is you native language, is english better?

**Comment by shownb** [comment]
may be english is better.i tried to get the usefull things from the Bin yesterday,but got little usefull information.
most of the xz file can not be decompress.May be it is a special format?
i hope you can rock it

**Comment by majuss** [comment]
I looked at firmware and I have to disappoint you... Vodafone decided to encrypt the firmware (after huge security leaks were published) and close it to all modifications. Without the crypto-key we can't change anything :(

**Comment by shownb** [comment]
may be we can replace the elf file in the bin dictionary that we can get in the squashfs?

**Comment by majuss** [comment]
No there is no way to sign the modified firmware.

**Comment by majuss** [comment]
The guide got completely rewritten please try it again!

**Comment by majuss** [comment]
Please open a new issue if you have troubles.
