### ISSUE TITLE
Voip funktioniert nicht

### ISSUE THREAD

**Issue by tadschik** [majuss/easybox904#11]
Easybox 904 geflasht, DSL-Verbindung funktioniert soweit. Telefonie leider nicht. Auszug aus dem log /var/log/ppp.log
```
Plugin rp-pppoe.so loaded.
Interface ptm0.132 has MTU of 1492 -- should be 1500.  You may have serious connection problems.
Timeout waiting for PADO packets
Unable to complete PPPoE Discovery
ioctl(PPPIOCSNPMODE, 33, 0): Bad file descriptor
ioctl(PPPIOCSNPMODE, 87, 0): Bad file descriptor
Interface ptm0.132 has MTU of 1492 -- should be 1500.  You may have serious connection problems.
Timeout waiting for PADO packets
Unable to complete PPPoE Discovery
ioctl(PPPIOCSNPMODE, 33, 0): Bad file descriptor
ioctl(PPPIOCSNPMODE, 87, 0): Bad file descriptor
Interface ptm0.132 has MTU of 1492 -- should be 1500.  You may have serious connection problems.
receivePacket: recv: Network is down
Plugin rp-pppoe.so loaded.
Interface ptm0.7 has MTU of 1492 -- should be 1500.  You may have serious connection problems.
Timeout waiting for PADO packets
Unable to complete PPPoE Discovery
ioctl(PPPIOCSNPMODE, 33, 0): Bad file descriptor
ioctl(PPPIOCSNPMODE, 87, 0): Bad file descriptor
Interface ptm0.7 has MTU of 1492 -- should be 1500.  You may have serious connection problems.
[waitForPADS] PPP session is 58
[set_ifunit] Using interface ppp50
[start_link] Connect: ppp50 <--> ptm0.7
Couldn't increase MTU to 1500
Couldn't increase MRU to 1500
PAP authentication succeeded
PAP authentication succeeded
peer from calling number 2C:21:31:2C:B7:64 authorized
kernel does not support PPP filtering
local  IP address 91.6.34.217
remote IP address 62.155.243.238
primary   DNS address 217.0.43.145
secondary DNS address 217.0.43.129
```

**Comment by majuss** [comment]
Welcher Provider? Ich kann leider auch nicht so viel mit dem log anfangen.

**Comment by tadschik** [comment]
Telekom

Interessant wahrscheinlich dieser Teil

Timeout waiting for PADO packets
Unable to complete PPPoE Discovery

Habe dazu noch diese Seite gefunden
https://layer9.wordpress.com/2010/02/09/dsl-verbindung-mit-t-dsl-business-pppoe-und-debian-lenny/

Zitat:
"Wird der pppd während dieser Phase beendet, dauert es bis zum tatsächlichen Schließen des Prozesses bis zu 30 Sekunden. Da das Script aber schon nach fünf Sekunden eine neue Verbindung aufbauen möchte und zuvor auf bestehende Prozesse prüft, bricht das Script ab und der pppd wird nicht neu gestartet."

**Comment by majuss** [comment]
Also VOIP funktioniert bei mir problemlos, du musst etwas falsch eingegeben haben oder du hast gar kein VOIP Anschluss (gibt es vereinzelt immer noch). Vlt. hast du den Area Code/ Vorwahl falsch eingegeben? zB. bei "ccfg_cli set userId@sip_acc_1" sollte es so aussehen: 03044567321. 030 ist hierbei die Vorwahl deines Landkreises.

**Comment by majuss** [comment]
Wie siehts aus? Ansonsten schließe ich den issue.
