### ISSUE TITLE
O2 feasibility?

### ISSUE THREAD

**Issue by zedbrett** [majuss/easybox904#12]
Hey majuss,
thanks for your description.
I am trying to configure it for O2 VDSL, but without any success. I uploaded the firmware and changed everything by using a ssh connctin with putty. Still no connection.

Maybe you have an idea?
Thanks

**Comment by majuss** [comment]
You need to add an capital "H" at the beginning of your username. You have to google the stuff for details.

**Comment by zedbrett** [comment]
You mean like this? 

ccfg_cli set username@wan050=H<myusername>@s93.bbi-o2.de
ccfg_cli set password@wan050=<mypassword>
ccfg_cli set vlan_id@wan050=7

The only google results for O2 and easybox is this topic and another, where you are helping some guy. It is O2 Germany btw

**Comment by majuss** [comment]
Yes this is maybe right (no idea, since I can't test it at all you know :D). You don't have to google for the EB google for the manual DSL setup or the setup with a Telekom Speedport.

**Comment by zedbrett** [comment]
Actually I did not find anything about modifying the username (the link is about a LTE problem). My login data are working in a speedport without any problems.
I will give up :D Thank you anyway for sharing your stuff

**Comment by majuss** [comment]
Any news on that?

**Comment by oliverpool** [comment]
Hi,

thank you so much for the guide !

I've been able to have a working DSL connection with O2 with the following config (taken from the "Die wichtigsten Informationen"):
```
ccfg_cli set username@wan050=089********@s93.bbi-o2.de
ccfg_cli set password@wan050=******
ccfg_cli set vlan_id@wan050=7
```
Interestingly, just after booting, the box is able to connect to the internet (according to http://easy.box ), and then synchronizes the time (via NTP). After that, the internet connexion is reset and it takes about 5 minutes to have a working connexion!

I've not been able to completely set-up SIP for the VOIP (see #20)
