### ISSUE TITLE
Anyone managed to work with 1und1?

### ISSUE THREAD

**Issue by misterbyte** [majuss/easybox904#13]
Hi,
thanks for the great Guide which worked great.

Unfortunately it does not work with 1und1. I always get a PAP authentication error when I check the ppp.log. 

According to the guide I used:

ccfg_cli set username@wan050=1und1/<number>@online.de
ccfg_cli set password@wan050=[Password]

and verified that all is correct but it won't connect.

Has anyone an idea what could be wrong?

Thanks!

**Comment by majuss** [comment]
Why did you closed the Issue? Could you fix the Login? You should look around for the manual DSL(ppoe)  configuration for 1&1. Maybe there are some key charakters needed, like the "#" for Telekom.

**Comment by misterbyte** [comment]
Don't know why but after changing the password on the 1und1 portal and on the easybox it worked. For all also using it with 1und1 the username is: 1und1/XXXX-XXX@online.de
