### ISSUE TITLE
What is there to see from the shell?

### ISSUE THREAD

**Issue by T-E-N** [majuss/easybox904#14]
Experiences with these or more on the 904, anyone?
- logread from in-memory logger
- an unconfigured lighttpd binary for one thing (might come in handy e.g. for smarthome/domotics)
- dnsmasq - maybe these boxen can become better local DNS than Arcadyan's usually lame approach?
- any usable DSL diagnostics more advanced than the rather terse web interface (which once was verbose on the 802) ?

**Comment by majuss** [comment]
I think you should watch at the openWRT branch for this Project, as mentioned in the README :)
