### ISSUE TITLE
?: 904 xDSL debrick guide: pinout serial connector? / box behaviour after R148 shortcut?

### ISSUE THREAD

**Issue by M0RT1M4R** [majuss/easybox904#15]
Hi,

thank you very much for the guide.
I am struggling maybe because I try to use my Raspberry with its build in serial port ;-)

But I do also have a few questions which I could not figure out by myself or with the help of google so far.
Hope you could shed some light here.

**How is the behaviour of the box after R148 was shortcut?**
I am asking because I screen sometimes lights up only the background lights but nothing more sometimes stays black, sometimes as well the navigation lights turn on but there is no normal start process like without R148 shortcut. Is that normal?

**How do I have to connect the GND, Tx, Rx to the pins on the 904xDSL board?**
From the linked picture I am not able to tell and other picture I found are not clear to me as well.
Do I have to connect power to one of the pins as well? If yes which one is that and how much is the voltage?
Maybe you could enhance the picture with that information like here (https://wiki.openwrt.org/_media/media/arcadyan/easybox_904_lte_pinout.jpg?cache=) >> unfortunately the wrong model.

Thank you very much

bye morT

**Comment by majuss** [comment]
When you shortcut the Pin you're getting the box into serial recovery mode. So it will act strangely.

Here you can see the pinout: https://wiki.openwrt.org/inbox/arcadyanastoria/arcadyan_astoria_easybox_904xdsl_r01#serial
Will add this to the guide for sure!

**Comment by majuss** [comment]
closed, will be added with next commit
