### ISSUE TITLE
bootloop! modem is not starting anymore

### ISSUE THREAD

**Issue by SasanAhmadi** [majuss/easybox904#16]
Hi 

I did setup a tftp server and put the image on it, modem had run in rescue mode and image copied. from then on it has never been started anymore! poweron-> vodafone logo-> wait message... -> blank screen -> [repeat the past two step for several times ] -> a message showed up saying you should reset your modem to factory setting which I tried many times and was not successful !

also did download the original image from vodafone website -> uncompress and rename to fullimage.img and repaet again, but no success !

what should I do ?

**Comment by majuss** [comment]
Sorry for the late answer. Just follow the debricking guide here in this repo. You will need to buy a serial USB console.
