### ISSUE TITLE
WAN auf Ethernet (dhcp) konfigurieren?

### ISSUE THREAD

**Issue by wapolinar** [majuss/easybox904#17]
Weiß zufällig jemand, ob man den WAN-Port auch so konfigurieren kann, dass das Gerät quasi direkt per DHCP hinter einen existierenden Router gesteckt werden kann? Man also quasi das ADSL-Modem umgeht?

Hintergrund: Ich habe das Gerät noch übrig und würde es gerne als ISDN->VoIP-Gateway hinter meiner bestehenden Router-Konfiguration nutzen. Nach dem Flashen habe ich zwar verschiedene wan-Profile entdeckt, bei diesen das VLAN zu deaktivieren und auf dhcp zu konfigurieren hat allerdings nicht zum Erfolg geführt.

Achso: SUPER Anleitung! War wirklich extrem hilfreich und das Gerät ist ja eigentlich auch ein potentes OpenWRT-Gerät.

**Comment by majuss** [comment]
Kann ich dir leider nicht genau helfen. Geht bestimmt irgendwie ;) 
Möchtest du das Gerät jetzt als Modem oder als Router verwenden?

**Comment by wapolinar** [comment]
Ja, das hatte ich befürchtet.
Im Endeffekt soll es dann nur ein Router sein. Die Frage ist allerdings, ob man den WAN-Port wirklich überzeugen kann nicht über das Modem zu gehen.

**Comment by wapolinar** [comment]
Es gibt besondere Geräte mit WanOE (WAN over Ethernet)-Ports, wie den Zyxel 5501, bei dem dies möglich ist. Ich vermute einfach, dass man um das Modem nicht herumkommt.

Da sich bisher niemand gemeldet hat, schließe ich den Issue. Falls es doch noch einen Weg gibt das Modem zu umgehen, kann man ihn ja wieder öffnen.

**Comment by Matzeee** [comment]
Hallo @wapolinar, wenn auch nun vermutlich nicht mehr relevant und eher zur Dokumentation: Ich habe die gleiche Frage im OpenWRT-Forum gestellt, sehr schnell eine Antwort bekommen und es funktioniert!

Habe bisher nur die Variante mit Ethernet Wan (dhcp) am dsl Port getestet und das klappt einwandfrei mit dem aktuellsten Build (18.10.2020) von Plonk34:

https://forum.openwrt.org/t/support-for-easybox-904-lte/14478/338
https://forum.openwrt.org/t/lantiq-xrx200-easybox-904xdsl-and-speedport-w-921v-build/77105

Wlan muss nach wie vor über ssh konfiguriert werden, läuft dann aber einwandfrei.

**Comment by wapolinar** [comment]
Hi @Matzeee , danke für die Info. Bin mir nicht ganz sicher, ob mit OpenWRT ISDN noch funktioniert, aber die Konfigurationstipps helfen vielleicht auch schon bei der ursprünglichen Firmware (wobei man dort ja glaube ich nur das NVRAM anpassen kann).
Danke auf jeden Fall für diese Rückmeldung, sowas hat man selten! :-)
