### ISSUE TITLE
Fehlercodes 812 und 814

### ISSUE THREAD

**Issue by Eshatos** [majuss/easybox904#19]
Hallo,
ich habe meinen Telekomanschluss über ssh als VDSL konfiguriert und auch den Punkt "Activation" nicht vergessen. Trotzdem bekomme ich die Fehlercodes 812 und 814...
Weis jemand vielleicht Rat?

**Comment by majuss** [comment]
Ist es ein vectoring Anschluss? Funktioniert der Anschluss mit einem anderen Router? Hast du noch einmal alles von vorn eingegeben um Fehler komplett auszuschließen? Wie hast du die Zugangsdaten eingegeben (nach welchem Muster)?

**Comment by Eshatos** [comment]
Hallo, 

Also der Anschluss funktioniert mit einer alten Fritzbox 7360 und wird dort als VDSL2 Anschluss angezeigt. So weit ich weiß handelt es sich um ein Magenta Tarif ohne Entertain Option. Die Zugangsdaten hab ich nun schon mehrmals nach diesem Muster eingegeben: ccfg_cli set username@wan050=[Anschlusskennung][T-Onlinenummer]#0001@t-online.de

Hab es auch schon mit und ohne eckige Klammern ausprobiert. Vielen Dank für deine Mühe schon mal im voraus.

**Comment by Eshatos** [comment]
Natürlich habe ich auch die weiteren "ccfg_cli set" Befehle für die VDSL Konfiguration nicht vergessen und zum Schluss:

Activation:

ccfg_cli set ivr_mode@bootstrap=2
ccfg_cli set arcor_pinConf@bootstrap=1
ccfg_cli set arcor_customer@bootstrap=1
ccfg_cli set keep_in_act@bootstrap=0
ccfg_cli set FirstUseDate@tr69=2015-05-24T01:07:49

Save Changes:

ccfg_cli commitcfg

**Comment by majuss** [comment]
'222222222222111111111111#0001@t-online.de'

Du musst es zwingend nach diesem Muster eingeben. Alle Zweien sind deine Anschlusskennung. Die Einsen die Zugangsnummer.

**Comment by Eshatos** [comment]
So hatte ich es auch schon versucht,  gut ich werde es jedoch nochmal versuchen.  Kann dies aber erst wieder in zwei Wochen,  melde mich dann ob es geklappt hat oder nicht.

**Comment by shamsuzzamansadi** [comment]
Wir haben die Anleitung für ADSL (da wir nur eine 16000er Leitung haben) befolgt und aktiviert und erhalten den Fehlercode 812 erhalten. Wir können das Routermenü 192.168.2.1 öffnen, dort wird angezeigt das ein Download mit 16 Mbit/s besteht. Aber ein Ausrufzeichen ist zu sehen, außerdem wird kein IP, Gateway, Primary sind ohne Angabe. Unser Anbieter ist o2.

**Comment by majuss** [comment]
@shamsuzzamansadi https://github.com/majuss/easybox904/issues/12#issuecomment-375456256
Guck dir das mal an, vlt. hilft es :)

**Comment by shamsuzzamansadi** [comment]
@majuss vielen Dank für deinen Hinweis. Wir haben einen Usernamen mit folgenden Format DSL*********@s92.bbi-o2.de - möglicherweise weil hier nur ADSL verfügbar ist. Nun die Frage: Sollen wir auch die USB-Stick Variante versuchen? und Wie sollen wir den Username angeben da dieser von deiner Referenz abweicht und trtotzdem als VDSL probieren? Wir hatten schon VDSL versucht aber mit unserem Nutzernamen - daher DSL****@s92.bbi-o2.de - dies hat damals nicht funktioniert.
