### ISSUE TITLE
"SSH Easy" Befehl klappt nicht

### ISSUE THREAD

**Issue by RobiWa** [majuss/easybox904#2]
Hallo,
die Firmware wurde auf meine Easybox Übertragen allerdings komme ich nicht mit dem Befehl 
"ssh easy" weiter.

Es kommt immer:

Permission denied (publickey)

Der SSH Key am Anfang der Anleitung habe ich kopiert und dieser stimmt auch.

Hast du zufällig noch einen Tipp woran das liegen kann?

**Comment by majuss** [comment]
Versuch mal "ssh easy -vv" und poste den output.

**Comment by RobiWa** [comment]
Danke für die schnelle Antwort.
Also Output ist:

anu@linux:~$ nano .ssh/config
anu@linux:~$ sudo -s
root@linux:~# ssh easy -vv
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for easy
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Hostname has changed; re-reading configuration
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to 192.168.2.1 [192.168.2.1] port 22.
debug1: connect to address 192.168.2.1 port 22: Connection refused
ssh: connect to host 192.168.2.1 port 22: Connection refused

**Comment by majuss** [comment]
okay dann noch ``cat .ssh/config``

**Comment by RobiWa** [comment]
Also das wäre:

root@linux:~# cat .ssh/config
cat: .ssh/config: Datei oder Verzeichnis nicht gefunden

Allerdings existiert es eig:

root@linux:/home/anu/easyboxhack/squashfs-root# cd --
root@linux:~# cd .ssh
root@linux:~/.ssh# ls
config  id_rsa  id_rsa.pub  known_hosts
root@linux:~/.ssh# 

Verstehe das nicht ganz, oder mache ich was falsch?

**Comment by majuss** [comment]
Wo ist deine ssh-config datei? Sie sollte in ``/home/anu/.ssh`` sein. Bitte poste sie. Und dann nicht unter ``root`` verbinden sondern als normaler user. Also nochmal ``exit``

**Comment by RobiWa** [comment]
Okay.. ich habe es allerdings alles unter root gemacht, dürfte ja eigentlich kein Unterschied machen oder?

root@linux:~# cat .ssh/config
Host easy	
	Hostname 192.168.2.1
	User root
	Identityfile ~/.ssh/id_rsa
	KexAlgorithms diffie-hellman-group1-sha1

**Comment by majuss** [comment]
Erstell mal das config file unter deinem User und connecte dich per ssh mit deinem User nicht root! Checke auch alle file-permissions. Hast du den USB Stick an der easybox mit dem sesame.txt?

**Comment by majuss** [comment]
Hat es jetzt geklappt? Neues Terminal auf, ohne root. ``/$username/.ssh/config`` checken und mit ``ssh easy`` verbinden.

**Comment by RobiWa** [comment]
Danke für die Hilfe, ich probiere es gleich aus und gebe bescheid! :-)

**Comment by majuss** [comment]
The guide got completely rewritten please try it again!

**Comment by RobiWa** [comment]
Okay, danke ich gebe die Tage nochmals Rückmeldung und Spiele nochmals alles durch !

**Comment by RobiWa** [comment]
Also, die englische Anleitung hat sehr gut Funktioniert. DSL Läuft allerdings leider noch nicht mein Telefon.

Kurze Frage:

VOIP:

ccfg_cli set lineEnable@sip_acc_1=1
ccfg_cli set userId@sip_acc_1=[AreaCode][PhoneNumber]           <-------------
ccfg_cli set userId_area@sip_acc_1=[AreaCode]                            <-------------
ccfg_cli set userId_local@sip_acc_1=[PhoneNumber]                      <-------------
ccfg_cli set account_name@sip_acc_1=[AreaCode][PhoneNumber]  <-------------
ccfg_cli set displayName@sip_acc_1=[AreaCode][PhoneNumber]         <-------------
ccfg_cli set password@sip_acc_1=
ccfg_cli set useAuthId@sip_acc_1=0
ccfg_cli set authId@sip_acc_1=
ccfg_cli set realm@sip_acc_1=tel.t-online.de
ccfg_cli set sipdomain@sip_acc_1=tel.t-online.de
ccfg_cli set registrar@sip_acc_1=tel.t-online.de
ccfg_cli set proxy@sip_acc_1=tel.t-online.de
ccfg_cli set outboundProxy@sip_acc_1=tel.t-online.de
ccfg_cli set useOutboundProxy@sip_acc_1=0
ccfg_cli set useDNSSRV@sip_acc_1=1
ccfg_cli set dtmfTxMethod@sip_acc_1=1

Bei den Kästchen mit Area Code und Phone Number, muss diese in die [   ] geschrieben werden oder muss ich diese  wegmachen?
Quasi [064263578XXX] oder einfach nur 064263578XXX ohne die [   ].

Auch verstehe ich nicht ganz die Schreibweise der Telefonnummer muss davor noch ein Ländercode wie +49 ?... werde aus den Telekom Informationen auch nicht ganz schlau.

Ist es auch möglich mehrere Rufnummern hinzuzufügen? habe von der Telekom 3 Rufnummern bekommen?

Vielleicht hast du noch eine Antwort auf meine Frage :)

**Comment by majuss** [comment]
Q1: Einfach nur: 064263578XXX. Area Code steht für Vorwahl und die Klammern sind nur um die "Variablen" voneinander zu trennen, zur besseren Lesbarkeit.

Q2: Nein kein Ländercode, Areacode = Vorwahl (zb. 030 für Berlin).

Q3: Was verstehst du bei den Telekominformationen nicht? Das sind nur die Proxies etc. für SIP.

Q4: Klar mehrere Nummern sind problemlos möglich. Siehe ``ccfg_cli set userId_local@sip_acc_1=`` Dort steht ja ne 1 am Ende ;) Einfach alle Optionen die eine Zahl dran haben ebenso für die 2,3.. etc. eintragen.

**Comment by RobiWa** [comment]
Okay danke dann habe ich es glaub falsch gemacht, werde es sofort nochmals Abends testen und gebe Rückmeldung

**Comment by RobiWa** [comment]
Also es hat alles ohne Probleme funktioniert.
Das komische ist ich hatte 2 EasyBox 904x Router, mit einem ging alles ohne Probleme, beim anderen kam immer "Port 22 Connection Refused" auch auf anderen Ports ging es nicht. Beim anderen ohne Probleme.
Man muss dazu sagen der Fehler kam beim Image das hier fertig eingestellt wurde.
Beim eigenen erstellen der Firmware ging es komischerweise ohne Probleme. Woran es genau liegt kann ich nicht sagen.
Im Allgemeinen ging es dennoch sehr schnell und einfach ! Danke nochmals dafür und die sehr gute Anleitung die bestimmt vielen hier helfen wird!

**Comment by majuss** [comment]
Mich freut es das ich dir helfen konnte :)

**Comment by T-E-N** [comment]
Muß vor "ssh easy" nicht erst ssh-keygen (obwohl in der Kurzanleitung unerwähnt) auf dafür verwendeten System und unter zur Anmeldung eingeloggtem User laufen, damit dessen ~/.ssh folgende Dateien enthält?

id_rsa  id_rsa.pub

Oder müssen diese beiden vielmehr exakt die vom Ersteller des https://github.com/majuss/easybox904/blob/master/fullimage.img verwendeten (aber bislang nicht zum Download verfügbaren) sein, um zum Gegenstück im fertigen Image zu passen, damit dieses nicht jeder neu mit eigenem Schlüsselpaar bauen muss?

**Comment by majuss** [comment]
Der ssh-key ist sowieso sinnfrei. Es erfolgt ein Login über das Passwort ohne key, soweit ich das in Erinnerung habe. Kannst ja mal alles durchprobieren, aber ich denke mal der key ist Wurst.
