### ISSUE TITLE
Wie werden drei Telefonnummern eingetragen?

### ISSUE THREAD

**Issue by bobybobybob** [majuss/easybox904#22]
Wie werden drei Telefonnummern eingetragen und den Analog Anschlüssen zugewiesen?

und geht der ISDN Ausgang der Box?

**Comment by majuss** [comment]
Du solltest mit der richtigen config in der Lage sein ein ISDN Telefon zu benutzen, solange dein Anschluss es zulässt. Mehrere Telefonnummern lassen sich genauso konfigurieren wie eine einzelne. Schau dir die komplette config mit `ccfg_cli showcfg` an und such die entsprechenden Parameter, sind leider etwas über 3000 Zeilen. Aber eine schnelle suche nach ISDN, ergibt:

`isdn_area_code@isdn =
AddISDNNumberAllowed@isdn = 1
msn_number_0@isdn =
msn_name_0@isdn =
`

**Comment by bobybobybob** [comment]
Dauert noch eine Woche bis ich VDSL habe und es mit dem ISDN Testen kann, aber seit heute habe ich diese Box und gemäß der Anleitung funktioniert pures Internet über DSL sehr gut. 

ccfg_cli showcfg zeigt mehr an als was das Terminalfenster speichern kann. Wie bekomme ich alles zu sehen?

**Comment by bobybobybob** [comment]
In paar Tagen geht es los mit der Umstellung

Muss bei der Umstellung von DSL zu VDSL die Einträge bei 
username@wan000 und password@wan000  leer gemacht werden?

Und bei der Telefonie bleiben die zwei Einträge da wirklich leer? Oder muss da gemäß dieser Seite https://www.telekom.de/hilfe/festnetz-internet-tv/ip-basierter-anschluss/einstellungen-fuer-die-ip-telefonie-mit-anderen-clients?samChecked=true  eine T-Online Emailadresse mit Email-Passwort eingerichtet werden was da dann eingetragen wird?   Bzw. da meint einer https://telekomhilft.telekom.de/t5/Telefonie-Internet/Voip-Zugangsdaten/td-p/808741/page/2   die Zugangsnummer (T-Online-Nummer) und das DSL Passwort?   

ccfg_cli set password@sip_acc_1=
ccfg_cli set authId@sip_acc_1=

**Comment by bobybobybob** [comment]
Fazit:

VDSL Daten eintragen während man noch DSL nutzt funktioniert, hat aber keinen Vorteil weil nach der Umschaltung auf VDSL die Easybox sich nicht einwählt. Mann muss die die zwei DSL Einträge mit dem ccfg_cli unset   entfernen und evt. nochmal das ccfg_cli set vlan_id@wan050=7     

Easybox syncroniert mit 106 mbit

Die VoIp Anmeldung hat einen Tag vor Umstellung mit DSL funktioniert. Nach der VDSL Umschaltung stand nur fehler. Nach dem ich bei VoIp bei authid die T-Onlinenummer und bei passwort das DSL Passwort eingetragen habe waren alle drei dann angemeldet. 

ISDN der Telefonanlage an die Easybox angesteckt und bei Eingehende und Ausgehende jeweils den ISDN S0 gewählt. 

Anrufen ging, angerufen werden nicht. Ich habe mit den isdn_area_code@isdn = AddISDNNumberAllowed@isdn = 1 msn_number_0@isdn = msn_name_0@isdn =    Werten herumgespielt aber ich hatte den Eindruck das diese Eingaben großteils nicht angenommen wurde. 

Nach etwa zwei Stunden hat ohne weiteres zutun auch das Angerufen werden funktioniert. Nun geht alles. Super und danke an majuss

**Comment by majuss** [comment]
Wow vielen Dank für das Feedback! Mich freut es, dass dein Geldbeutel und die Umwelt geschont werden konnten!
