### ISSUE TITLE
Deutsche Anleitung

### ISSUE THREAD

**Issue by Brother00** [majuss/easybox904#23]
Hallo, gibt es eine aktuelle Deutsche Anleitung? Geht es auch nur mit Windows 10? Danke und viele Grüße

**Comment by majuss** [comment]
Nein es gibt noch keine aktuelle deutsche Anleitung. Jein mit Windows geht es zwar, aber einige haben sich damit ihre easyBox zerschossen. Am sichersten ist ein Debian Live. Wenn du Hilfe brauchst kannst du mich auch per E-Mail kontaktieren, dann können wir das über TeamViewer / Skype machen.

**Comment by Brother00** [comment]
Ich habe leider kein Debian Live. Ich wechsel aber erst im Juni zu der Telekom daher hab ich eh noch keine Daten für die Einrichtung.

Von: majuss
Gesendet: Samstag, 21. April, 09:58
Betreff: Re: [majuss/easybox904] Deutsche Anleitung (#23)
An: majuss/easybox904
Cc: Brother00, Author


Nein es gibt noch keine aktuelle deutsche Anleitung. Jein mit Windows geht es zwar, aber einige haben sich damit ihre easyBox zerschossen. Am sichersten ist ein Debian Live. Wenn du Hilfe brauchst kannst du mich auch per E-Mail kontaktieren, dann können wir das über TeamViewer / Skype machen.

**Comment by majuss** [comment]
Debian live kannst du dir doch kostenfrei herunterladen und auf einen USB stick kopieren, dauert keine 5 Minuten und du hast Debian :)

**Comment by Brother00** [comment]
Hast du einen Link? Habe irgendwo gelesen man braucht Linux um diesen Stick zu erstellen?
________________________________

**Comment by majuss** [comment]
Einfach das image herunterladen: https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/9.4.0-live+nonfree/amd64/iso-hybrid/debian-live-9.4.0-amd64-xfce+nonfree.iso
Und mit Rufus: https://rufus.akeo.ie/ auf ein USB Stick bringen.

**Comment by Brother00** [comment]
Alles klar Danke für die Info. Kann ich mich dann Melden wenn ich alle Daten habe?
________________________________

**Comment by majuss** [comment]
Klar dann bitte an ich@majuss.de

**Comment by Brother00** [comment]
Korrekt, Danke und bis dann??
________________________________

**Comment by bobybobybob** [comment]
Ich hab das Image verwendet und Fernsteuerung dann mit Putty
IP: 192.168.2.1 port 22
Connection ==> Data ==> Auto-login username: root
SSH ==> SSH protocol version 2
SSH ==> Auth ==> Haken bei SSH-1 

Wenn man später die IP und oder Login-Passwort des Routers ändert ändert sich auch die Adresse für Putty. Funktioniert auch über WLAN.

**Comment by majuss** [comment]
Klar wenn du dich auskennst geht es :) nur leider ist die bricking Wahrscheinlichkeit unter Windows meines Erachtens wesentlich höher.
