### ISSUE TITLE
Instruction improvement

### ISSUE THREAD

**Issue by eico1013** [majuss/easybox904#24]
Hi Majuss,

first of all thanks for your efforts putting in this project 🥇 
I successfully switched from vodafone to telekom.
But there were some difficulties.

In the following some suggestions for your migration instructions:

Linux Distribution on Windows:
You can use a windows app running linux on your windows10. This is a lot easier than mounting a usb drive.
https://docs.microsoft.com/en-us/windows/wsl/install-win10

3. i couldn't stop network-manager, because there was no network-manager installed.
I had to set the ip multiple times, because dhcp was active. I guess there is another way too.
on the newest linux distributions the network adapters are not eth0,eth1... 
you have to find out with `ifconfig`

6. I could not write the file .ssh/config (maybe because i was a the root user)
other option i used:
`ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 root@192.168.2.1`

7. I didn't know that i had to set adsl + vdsl this is important ! i only set vdsl
Please give hint that AreaCode = is not the country code. Had to search in the last issues :)
Helpfull command for writing all configs of the easybox: 
`ccfg_cli showcfg`
Read specific configuration
`ccfg_cli get xxx`

**Comment by majuss** [comment]
Thanks for the feedback 👍 
I will implement everything in the next few weeks :)

**Comment by majuss** [comment]
I still didn't got the leisure to update the guide... I will try it in the next days!

**Comment by homerograco** [comment]
hi @eico1013 Which provider do you use? I actually only set ADSL (I have Deutsche Telekom DSL), and I am getting proper connection.
