### ISSUE TITLE
VOIP/ISDN 1und1 - keine ausgehenden anrufe - no outgoing calls

### ISSUE THREAD

**Issue by Redsed610** [majuss/easybox904#25]
Hallo,
danke für den guide. Ich hab Internet soweit zum Laufen bekommen, aber beim Telefon kommen zwar Anrufe an, beim eigenen Anrufen nur durchgehendes Piepen/Besetzt Zeichen.
Konfiguriert hab ich folgendermaßen:

ccfg_cli set lineEnable@sip_acc_1=1
ccfg_cli set userId@sip_acc_1=49[Area Code ohne Null][PhoneNumber]
ccfg_cli set userId_area@sip_acc_1=[AreaCode mit Null und ohne Null(beides getestet)]
ccfg_cli set userId_local@sip_acc_1=[PhoneNumber]
ccfg_cli set account_name@sip_acc_1=49[Area Code ohne Null][PhoneNumber]
ccfg_cli set displayName@sip_acc_1=49[Area Code ohne Null][PhoneNumber]
ccfg_cli set password@sip_acc_1=[1und1 VOIP Passwort]
ccfg_cli set useAuthId@sip_acc_1=0 [hier auch 1 ausprobiert, dann hat nichts funktioniert]
ccfg_cli set authId@sip_acc_1=49[Area Code ohne Null][PhoneNumber] - ([hier](https://www.ip-phone-forum.de/threads/sip-zugangsdaten-zu-1-1-zur-verwendung-in-softphones-etc.190728/) gelesen, bei 0 wohl überflüssig)
ccfg_cli set realm@sip_acc_1=1und1.de
ccfg_cli set sipdomain@sip_acc_1=sip.1und1.de
ccfg_cli set registrar@sip_acc_1=sip.1und1.de
ccfg_cli set proxy@sip_acc_1=sip.1und1.de
ccfg_cli set outboundProxy@sip_acc_1=sip.1und1.de
ccfg_cli set useOutboundProxy@sip_acc_1=0 [hier auch 1 ausprobiert, funktioniert beides bei eingehenden]
ccfg_cli set useDNSSRV@sip_acc_1=1 
ccfg_cli set dtmfTxMethod@sip_acc_1=1

Daten sonst [hierher](https://hilfe-center.1und1.de/dsl-hardware-c85325/fremd-hardware-c85411/konfigurationsdaten-1und1-telefonie-a796046.html).

Es ist noch ein STUN server von 1und1 angegeben, ich habe aber unter `ccfg_cli showcfg` nichts dazu gefunden. Hilft der?
Gibt es sonst noch Einstellungen, die ich übersehen habe?

**Comment by majuss** [comment]
Siehe: https://github.com/majuss/easybox904/issues/4

Könnte vielleicht helfen :)
Also überprüf deine Hardware und rupp alles weg was nicht unbedingt sein muss.

**Comment by majuss** [comment]
Any news? Otherwise I will close this issue.

**Comment by DDvO** [comment]
Mein Tipp aus leidvoller Erfahrung: Umstieg auf eine FritzBox. 
Siehe auch #20.

**Comment by Redsed610** [comment]
mitlerweile auf fritzbox umgestiegen, keine lösung gefunden
