### ISSUE TITLE
Keine Verbindung zum VDSL o2

### ISSUE THREAD

**Issue by Copy1989** [majuss/easybox904#26]
Leider klappt bei mir die Anleitung nicht.

Ich komm per SSH auf die Easy Box, habe von o2 den "Username" und "Passwort eingetragen" VLAN Tag auf 7. 

Was kann ich noch tun?

**Comment by majuss** [comment]
https://github.com/majuss/easybox904/issues/20

Hier das einmal durchlesen. 
`ccfg_cli set username@wan050=089********@s93.bbi-o2.de`
Der username für O2 muss ziemlich kryptisch eingegeben werden.

**Comment by Copy1989** [comment]
Also ich hab jetzt eigentlich alles durchgelesen, und viel versucht... leider kein Erfolg :(

Error Code FC812
Überprüfen Sie bitte die Verkabelung zwischen der Telefondose und der DSL-Buchse an ihrer EasyBox.
Error Code FC814
Die Verbindung ins Internet ist momentan nicht möglich.

![esyboxprob](https://user-images.githubusercontent.com/33970372/42452706-218430a4-838b-11e8-9045-b227b7bc88b2.JPG)

ccfg_cli set username@wan020="mit/ohne "H" "mit/ohne "DSL"1234567891234569@s93.bbi-o2.de
ccfg_cli set username@wan050="mit/ohne "H" "mit/ohne "DSL"1234567891234569@s93.bbi-o2.de

Verschiedene Kabel Probiert.

Bei o2 angerufen gefragt ob VLAN Tag 7 ok ist.... Ja ist so in Ordnung.
SIP Einstellungen durchgeführt wie im Post #20 


Entweder ich sehe vor lauter Bäume den Wald nicht mehr oder mein ISP o2 und Easybox vertragen sich nicht ^^

**Comment by Copy1989** [comment]
Hier kleine Update. Derzeit zeigt er mir VDSL Status an. Aber Internetverbindung ist nicht geschaltet. (siehe Screenshot )

![screenshot](https://user-images.githubusercontent.com/33970372/42532038-e4c565a6-8485-11e8-96e4-495fc23a279a.JPG)

Aber leider immer noch
Folgende Fehler bzw. Informationen liegen vor:
Error Code FC812
Überprüfen Sie bitte die Verkabelung zwischen der Telefondose und der DSL-Buchse an ihrer EasyBox.
Error Code FC814
Die Verbindung ins Internet ist momentan nicht möglich.

**Comment by DDvO** [comment]
Bei mir ging die DSL-Verbindung problemlos, wie angegeben mit:

```
ccfg_cli set username@wan050=DSL0000xxxxxxxxx@s93.bbi-o2.de
ccfg_cli set password@wan050=yyyyyyyyyy
ccfg_cli set vlan_id@wan050=7

ccfg_cli set ivr_mode@bootstrap=2
ccfg_cli set arcor_pinConf@bootstrap=1
ccfg_cli set arcor_customer@bootstrap=1
ccfg_cli set keep_in_act@bootstrap=0
ccfg_cli set FirstUseDate@tr69=2018-07-05T23:17:49

ccfg_cli commitcfg

reboot
```

**Comment by majuss** [comment]
Irgendwelche News? Ansonsten wird der issue geschlossen.

**Comment by Copy1989** [comment]
Für mich erledigt. Hab eigentlich nur warten müssen. 

Nach mehreren Tagen Testzeit ist mir aufgefallen das die Latenz Extrem im vergleich zur FritzBox unnormal hoch ist. (Ping an 1.1.1.1 50-60ms) 

Aus diesem Grund bin ich zur FritzBox 3370 gewechselt. (Ping an 1.1.1.1 8-10ms)

Danke für den Support!

**Comment by majuss** [comment]
Trotzdem danke für die Info das es geklappt hat :) Bei mir erst er ca. 10 ms höher als mit einem teuren Router. Damit kann ich leben. Wohlbemerkt verringert openWRT den Ping wieder auf das Niveau einer FritzBox.. Doch leider ist es noch sehr frickelig und von 100 Mbit werden maximal 75 erreicht.

**Comment by youngamazing** [comment]
@majuss dir erstmal tausend dank für das verbreiten deines geistigen eigentums ! mir hat das sehr geholfen nachdem meine fritzbox vermutlich durch einen blitzschaden nichts mehr gemacht hat !
@Copy1989 den Fehlercode hatte ich auch ! hättest halt echt einfach mal 10 Minuten warten müssen ! Danach gehts ! Also bei mir zumindest wars so ! ich hatte auch den Fehlercode 812 verkabelung prüfen.
Ich habe allerdings als der fehler erneut kam einfach mal wirklich das Kabel geändert und nun läuft die box seit gestern abend ohne Probleme !
