### ISSUE TITLE
Disable vlan_id

### ISSUE THREAD

**Issue by madin3** [majuss/easybox904#28]
Hi,
for my isp i need to disable the vlan_id@wan050.
How to do this?

Thanks in advance!

**Comment by majuss** [comment]
Hi, just run a: `ccfg_cli showcfg | grep vlan`
Look for the entry and disble it by setting it 0. 
`ccfg_cli set vlan_id@wan050 = 0`

**Comment by majuss** [comment]
@madin3 is your problem solved? If not just ask or try openWrt.
