### ISSUE TITLE
permission denied (publickey)

### ISSUE THREAD

**Issue by lyn1337** [majuss/easybox904#3]
Grüße,
ich bin den Schritten gefolgt und habe das image via tftp aufgespielt; scheitere nun am SSH Zugang mit im Titel benannter Fehlermeldung.
Über das Webinterface konnte ich auch kein "admin-Passwort" vergeben. Was mache ich falsch?

**Comment by lyn1337** [comment]
Es hat sich heraus gestellt, dass der SSHd nicht reagierte mit deplugged USB und dem im Tut zuerst gelinkten image.

**Comment by majuss** [comment]
Also die Schritte sind folgende:
1. Image flashen, mit USB Stick booten
2. Admin Kennwort setzen, Stick raus, reboot
3. 10 Minuten warten (!) dann ssh versuchen.

**Comment by T-E-N** [comment]
1. Image flashen, mit USB Stick booten
2. Admin Kennwort setzen, Stick raus, reboot

D.h. der USB-Stick musste zwingend beim ersten Boot nach dem Flashen
und beim ersten Setzen des Admin-Kennworts stecken - sonst komplett nochmal flashen?

Oder reicht es, einmalig mit gestecktem USB-Stick zu booten (man muß ja evtl. mehrere ausprobieren),
das Admin-Passwort per http://192.168.2.1 zu ändern
und dann die Box auszuschalten (oder soll der Reboot anderweitig angestoßen werden)?

**Comment by T-E-N** [comment]
>  reicht es, einmalig mit gestecktem USB-Stick zu booten (man muß ja evtl. mehrere ausprobieren),
das Admin-Passwort per http://192.168.2.1 zu ändern
und dann die Box auszuschalten?

Reicht offenbar

**Comment by majuss** [comment]
Einmaliger Boot reicht, PW einfach über die GUI ändern und dann über die GUI neustarten.
