### ISSUE TITLE
I am trying to use this in Serbia

### ISSUE THREAD

**Issue by mocnisima** [majuss/easybox904#30]
I am in Serbia, my network provider is beotel.net. My data: username=janko@beotel, password=janko015 vlanid=300.
I am trying to connect to vdsl 50/8 mbps with this:

ccfg_cli set username@wan000=janko@beotel
ccfg_cli set password@wan000=janko015

ccfg_cli set username@wan050=janko@beotel
ccfg_cli set password@wan050=janko015
ccfg_cli set vlan_id@wan050=300
ccfg_cli commitcfg
reboot 
but no result.
It just show me that my downstream/upstream is 50/8 mbps
Error 812 and 814.
Any advice what to do next?

**Comment by majuss** [comment]
Hi thank you for the interest in this project. Please wait 2-3 days til I finished and proofed my openWrt Guide. openWrt will work for sure :)

**Comment by mocnisima** [comment]
That is info from my provider. In the router that I got from them it is set to 300 and only with that it work.

**Comment by mocnisima** [comment]
![vlanid](https://user-images.githubusercontent.com/45820648/49870658-542f7f00-fe14-11e8-821b-7e028419e1df.PNG)

**Comment by mocnisima** [comment]
Ok thanks, I will wait then for your  openWrt Guide.

**Comment by mocnisima** [comment]
Any chance for openwrt soon?

**Comment by majuss** [comment]
Yes! Chances are very high, I will try the latest build from quallenauge tomorrow.

**Comment by majuss** [comment]
Still no luck :( latest image from end of december is crashing constantly.

**Comment by mocnisima** [comment]
This is serious work I will need hole day for this since I am windows user. 
I'll get back with feedback.

**Comment by mocnisima** [comment]
Well, after three days of battle I am successful. First problem with phyton path, then with umask and with starting tftp server ( you need to input sudo -i  first to be able to copy to tftpboot directory). This linux thing  - not for me. Now, I must enter my vlanid=300  but where do I put it?

**Comment by majuss** [comment]
It's not that easy. So when I understood correctly you have now openWrt up and running? Look at step 19. of the openWrt Guide. There we set the VLANID of the dsl to 7. You should enter a 300 there: dsl0.300. But then you need to change it as well in the switch underneath.
```
config switch_vlan
        option device 'switch0'
        option vlan '300'
        option ports '4t'
        option vid '300'
```

If you're very lucky this will work, but most likely the switch settings are different for your provider. If so you need to google for something like: "vlan id 300 openwrt", "boetel vlan 300", "boetel openwrt" etc. pp.

**Comment by majuss** [comment]
Ask them for an exact VLAN configuration and preferable a setup guide for openWrt devices.

**Comment by majuss** [comment]
Did you managed to get it working?

**Comment by mocnisima** [comment]
I gave up for now but I will try again when I find time.
