### ISSUE TITLE
Easybox wont load Image

### ISSUE THREAD

**Issue by Bernd123123** [majuss/easybox904#31]
Hey,

thanks for this guide.
After having some problems with my tftp setup yesterday, iam pretty shure that i set it up correctly today.
I could connect via both: 192.168.2.100 and 127.0.0.1 and successfully download the fullimage.img in the ftptpboot directory. And i checked via ifconfig, that the ip adress of my PC is indeed 192.168.2.100. also i did allow ftp in my firewall settings.
As far as i understand this is all if have to do for the easybox to automatically load the image when in rescue mode and connected via Lan.
But mine just doesnt. I get the red screen but then nothing ever happens. 

My ifconfig also shows a IPv6 adress. do i need to turn it off?

Thanks in advance for any help.

**Comment by majuss** [comment]
If you still have an IPV6 address you are still connected to a router. Please disable all Wifi etc. Your Computer should ONLY have the manually set IPV4. Which OS are you using?

**Comment by Bernd123123** [comment]
Im using Ubuntu. 18.04
Clean. just setup for this. on a stick.
I disabled the network-manager via systemctl stop, as you suggest in the guide.
but for using ifconfig i always have to install net-tools first.'
Also its a DesktopPC, so there is no WiFi card/adapter in it, as far as i know. It only should have Ethernet.
I also kinda tryied to set it up manually by not disabeling networkmanager and disabeling IPV6 in UI and set the IP adress in UI, but it didnt work either.

SO how do i disable all remaining Connections in Ubuntu? ANd is this also possible with a OpenTFTP from windows?

BUt thanks a lot for the fast answer.

**Comment by Bernd123123** [comment]
The other guide worked.
Thanks a thousand times!
