### ISSUE TITLE
Problem with no Splitter Telekom VDSL 50 IP 

### ISSUE THREAD

**Issue by kaiomatico** [majuss/easybox904#32]
Hello, thank you for your project. I try to Connect to Telekom Germany VDSL 50 IP without a Splitter. After setting everything up in ssh I get The correct 50mbit/s shown on the Vodafone Router web Interface, but I get no Connection and a red exclemation mark. The /var/log/ppp.log says that the MTU is 1492 instead of 1500. I also remember that half a year ago Telekom wrote me a letter that in the future no user login would be required, but I left the user login in my current Fritz box and everything still worked fine. Maybe you can point me in the right direction? Thx!

**Comment by majuss** [comment]
You can manually set the MTU. Just ssh onto the box and run: "ccfg_cli showcfg | grep mtu" and you're good to go. I would highly recommend the openWrt guide if you don't use the telephone functionality.

**Comment by kaiomatico** [comment]
P.s. I just saw that ccff_cli showcfg says annexJ@dsl = 0 , maybe this needs to be set to 1 for Operation without a Splitter?

**Comment by majuss** [comment]
Nope all german Telekom connections work with AnnexB 17a.

**Comment by majuss** [comment]
Hey no Problem :) you should double check if the MTU was saved correctly. Also make sure you set the MTU of the correct interface. Check it with `ifconfig`. Please post the full logs from /var/log etc.

**Comment by kaiomatico** [comment]
Your comment most likely is written before I edited my comment, sorry^^ Are you still interested in logs or should we close this issue now?

**Comment by majuss** [comment]
Ahh I see :) no you don't need to post anything, enjoy your cheap router :)!
