### ISSUE TITLE
[Question] your OpenWRT sysupgrade vs. Quallenauge

### ISSUE THREAD

**Issue by kaiomatico** [majuss/easybox904#33]
Hey, I installed OpenWRT following your guide recently and your build was stable, but I was not able to install samba-36 because the kernel version was incompatible. So I tried the build from Quallenauge, which had a nice interface on the display showing the CPU usage etc, but somehow crashed/reboots every 2 minutes.

So I would like to ask: Is your openwrt-sysupgrade.bin just the plain vanilla OpenWRT master branch with the 904.patch enabled or what else are the differences between the two builds? Is it possible you can include a kernel version which supports samba on this device? Thanks in advance 👍

**Comment by majuss** [comment]
I used quallenauges openWrt .config and deleted everything related to the LCD and lualnes. This way it's not crashing. If you need further assistance I can upload my .config.

**Comment by majuss** [comment]
I will compile one, check back this evening.

**Comment by kaiomatico** [comment]
Thank you very much for your effort! I will try to contact him.
