### ISSUE TITLE
error in step 13

### ISSUE THREAD

**Issue by Bernd123123** [majuss/easybox904#34]
Hi, 
just did it again for a friend and noticed there is a spelling error in step 13:

Now run: sudo cp Downloads/fullimage.img /var/lib/tftboot in a new Terminal window to copy the firmware image to the tftp-directory (close the old one).

it should be  /var/lib/tftpboot
the p is missing ;)

also along the way you need to activate Universe in Ubutunt and install 7zip maybe would be nice to add these 2 thing to your list.

thanks again for this great guide

**Comment by majuss** [comment]
Hey, thanks for the info! I will merge and test your suggestions in the near future.
