### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by homerograco** [majuss/easybox904#35]
Hey, thanks a lot for your tutorial, it helped me unlocking my router for Telekom!

I have some feedback to give:

1. For some reason I never managed to have tftp properly running in my machine Even though I configured it as shown in multiple websites, the router would never start downloading the firmware. Should it happen instantly, or does one need to be a little patient?
   1.1. Because tftp never worked for me, I looked for another way of writing the firmware, and it is actually very simple. With the router powered on and its setup page open in a browser (192.168.2.1), pressing the reset button for about 10 seconds will completely wipe its settings and send the browser to a new configuration page. There you will get 3 options: set a new password, activate the router and update the firmware. Simply use the last option, browse your computer to find the firmware file and voilà.
   1.2 Before discovering the trick above, I tried to simply open the management page (192.168.2.1) and trying to update the firmware from there, but for some reason it would tell me that the file was not appropriate. It is funny that after a full reset it does not perform the same checks (and because of that I believe one could potentially brick the device too - anyway you have a tutorial for that).

2. Everything good (almost), the router works and I am getting good download speeds on my devices. Except that my gf has a Pixel 3, and for some unknown reason she cannot load Amazon.de there. 
   2.1. We tried with Chrome, Firefox, Amazon app, none of them work.
   2.2. I also set the DNS to the Google ones (8.8.8.8 and 8.8.4.4), nothing either.
   2.3. Disabled firewall, and nothing.

   All other websites are loading normally for her, and really fast indeed. All other devices we have at home (PC, Mac, iPhone) have absolutely no issues, so we are really puzzled. Apparently some people are complaining about slow WiFi with the Pixel 3, but slow websites is very strange. Would you have any other idea, how could this possibly happen?

Again, thanks a lot for your help!

**Comment by majuss** [comment]
1.
Wow this is some interesting finding you made there. Where did you read it? (I actually never looked inside the manual :D)

2.
Can't help you on that... but it's most likely related to some adblocker/VPN/Proxy software which is installed on the Pixel. Only thing you can do: Reset the whole thing and see if it works out of the box.

**Comment by homerograco** [comment]
1. Alright, that's very interesting... I actually saw somebody online saying that, and a family member confirmed that he managed to reset his router doing the same trick. I am at work now and can't see which version is mine, but I can report back later.

2. The Pixel belongs to my GF, and I am almost sure she got no adblock or VPN there, but I can still check.

**Comment by majuss** [comment]
1. Yes I can also reset it, but I can't choose the openWrt starter image afterwards.

**Comment by majuss** [comment]
Guides got completely rewritten. I found out that you can only upload images in the webinterface with the appropriate filename and structure (openwrt will not work).

**Comment by homerograco** [comment]
Cool!
BTW, I completely disabled the firewall on the router with Busybox and suddenly Amazon started to work again for her. Not sure what was the issue in first place, but it seems to fix the problem.
