### ISSUE TITLE
Access Point

### ISSUE THREAD

**Issue by Chewb4cc4** [majuss/easybox904#36]
Hallo Majuss,
Ich würde die EasyBox gerne als AccessPoint nutzen. Habe auch schon versucht OpenWRT zu installieren, hat aber leider nicht funktioniert. Bin bei dem Befehl ‘make tool‘ hängen geblieben, da bei jeder Zeile permission denied stand. 
Hoffe du kannst mir da weiter helfen, denn ich würde das echt gerne hinbekommen

**Comment by majuss** [comment]
Mach einfach mal "sudo make tool" :)

**Comment by Chewb4cc4** [comment]
Die Antwort im Terminal:

Makefile:90: *** Running makefile as root is prohibited Please build Freetz as normal user. Stop

**Comment by majuss** [comment]
Oh ok, dann bitte den output wenn du es als normalen user laufen lässt.

**Comment by Chewb4cc4** [comment]
WARNING: The header file readline/readline.h was not found in /usr/(local/)include.
...........................................................................................
tools/genin: line 121: make/Config.in.generated: Permission denied
tools/genin: line 122: make/external.in.generated: Permission denied
tools/genin: line 130: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 126: make/Config.in.generated: Permission denied
tools/genin: line 130: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 126: make/Config.in.generated: Permission denied
tools/genin: line 130: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 132: make/external.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 126: make/Config.in.generated: Permission denied
tools/genin: line 130: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 134: make/Config.in.generated: Permission denied
tools/genin: line 140: make/Config.in.generated: Permission denied
tools/genin: line 144: make/Config.in.generated: Permission denied
tools/genin: line 145: make/external.in.generated: Permission denied
touch: cannot touch 'config/custom.in': Permission denied
make: *** No rule to make target 'tool'.  Stop.

**Comment by majuss** [comment]
Du befindest dich vlt. im welchen Ordner und er findet das alles nicht. Was sagt `pwd`?

**Comment by Chewb4cc4** [comment]
/home/jona/freetz-devel

**Comment by majuss** [comment]
Liegt an der umask des geklonten repos. Ich hab grad kein Linux und kann dir da nicht weiterhelfen, am WE setze ich mich ran.

Aber du brauchst das alles überhaupt nicht, weil du freetz-tools nur brauchst um die DSL Firmware einer FritzBox zu verwenden. Im AP-Modus brauchst du doch aber gar keine DSL Firmware?!

**Comment by Chewb4cc4** [comment]
Wie bekomme ich denn den AP Modus hin? Die EB hat die neueste FW drauf, habe keinen AccessPoint zum laufen gebracht

**Comment by majuss** [comment]
Na openWrt brauchst du schon... aber einfach ohne DSL setup.

**Comment by majuss** [comment]
Welches Linux hast du konkret versucht? Denn bei mir hatte Ubuntu Live 18.4 funktioniert.

**Comment by Chewb4cc4** [comment]
Habe eine Debian 64 bit Version über die VIrtualBox laufen lassen. Vielleicht ist das auch der Fehler.
Wo bekomme ich denn ein UbuntuLive 18,4 her, damit ich es nicht installieren muss?

**Comment by majuss** [comment]
Bzgl. Ubuntu Live ist alles in der Anleitung. Aber wie schon gesagt, brauchst ja gar kein Linux, denn die DSL Firmware ist ja sinnlos für dich.

**Comment by Chewb4cc4** [comment]
Bekomme das Firmwareimage aber unter Windows nicht aufgespielt, bzw. bin danach in einem Bootloop

**Comment by Chewb4cc4** [comment]
Habe es mit OpenTFTP versucht

**Comment by majuss** [comment]
Ah okay, ja irgendwie funktionieren die ganzen TFTP server unter windows nicht. Dann nimm Ubuntu live.

**Comment by Matzeee** [comment]
Ich habe auch vor, die Box als Access Point zu nutzen.
Könntest du kurz beschreiben, welches OpenWrt das ist?
Was funktioniert und was nicht?

Und komme ich von OpenWrt ggf über TFTP auch zurück zur originalen Firmware von Vodafone?

Geht die Variante mit der modifizierten Firmware von Vodafone eigentlich auch mit der aktuellen Version 04.13? Wäre ein Downgrade auf die beschriebene 03.17 nötig bzw möglich?

**Comment by majuss** [comment]
Das ist ein ganz normales openWrt angepasst für die EB. Kannste dir auch selbst kompilieren -> https://github.com/Quallenauge/Easybox-904-XDSL
Es geht so ziemlich alles außer SIP (ungetestet, aber sollte nicht gehen).
Zurück kommst du immer, ein echter unumkehrbarer Brick ist so gut wie unmöglich (und selbst wenn, dass Teil kostet 1€ ;) )

Ich arbeite gerade an der 4.13er fw, aber es wird noch einige Zeit in Anspruch nehmen. Der ssh-server wurde verändert, also nein im Moment wirds nicht gehen.

**Comment by majuss** [comment]
Guides wurden komplett neu geschrieben! Jetzt auch alles mit 4.13er firmware und neuestem openWrt!

**Comment by majuss** [comment]
Kann dieser Issue zu? Wie siehts aus mit dem AP?

**Comment by Matzeee** [comment]
Bin nun endlich dazugekommen, die Box als AccessPoint einzurichten.
Habe mit einem TFTP Server unter Windows10 (PumpKIN) zunächst das openwrt fullimage und dann über die Weboberfläche den Snapshot 2019-02-07 geflasht.

Wlan funktionierte, jedoch nur mit WEP und es ließen sich keine Kanäle etc einstellen. Daher wieder zurück auf die FW von Vodafone und einfach DHCP deaktiviert. Erfüllt seinen Zweck.

Braucht man für den reinen Betrieb als AC doch die Firmware aus der Fritzbox (Schritte 1-8)?

**Comment by majuss** [comment]
Die Konfiguration vom WLAN solltest du nicht im webinterface vornhemen (LuCi). Sondern per Terminal. 

https://openwrt.org/docs/guide-user/network/wifi/basic

Über LuCi ist sie komplett broken.

**Comment by Matzeee** [comment]
Vielen Dank, werde ich testen und den Durchsatz vergleichen!

**Comment by majuss** [comment]
Und was war dein Ergebnis :)?

**Comment by majuss** [comment]
Hast du nun eine Art Herangehensweise für den AP, oder hast du es aufgegeben?

**Comment by Matzeee** [comment]
Sorry für die sehr späte Rückmeldung.
Ich habe die Box in der Zwischenzeit mehrfach als günstigen AP mit der Originalen Firmware und deaktiviertem DHCP genutzt.

Nun hat ein Telekom Magenta TV an der Easybox nicht funktioniert. Die Firmware von Vodafone unterstützt offenbar kein Multicast. Mit OpenWRT klappt es nun aber ;)

Linux habe ich dafür gar nicht gebraucht. Kann nach wie vor http://kin.klever.net/pumpkin/ als TFTP für Windows empfehlen.

Vielleicht nützt noch jemanden die `/etc/config/wireless` (über das Webinterface lässt sich Wlan nach wie vor nicht konfigurieren):

```
config wifi-device 'wl000'
        option type 'ralink'
        option channel '36'
        option country 'DE'
        option disabled '0'

config wifi-iface 'default_wl000'
        option device 'wl000'
        option mode 'ap'
        option ssid 'SSID'
        option encryption 'psk2+aes'
        option key 'PASSWORD'

config wifi-device 'wl010'
        option type 'ralink'
        option channel 'auto'
        option disabled '0'
        option country 'DE'
        option htmode 'HT20'
        option hwmode '11g'

config wifi-iface 'default_wl010'
        option device 'wl010'
        option mode 'ap'
        option ssid 'SSID'
        option encryption 'psk2+aes'
        option key 'PASSWORD'
```
