### ISSUE TITLE
Box geht nich online

### ISSUE THREAD

**Issue by basiokan** [majuss/easybox904#37]
hi ich versuche mit vodadone VDSL online zu kommen, habe ich evtl irgendwo einen Fehler bei denn Settings?

folgendes gebe ich nach dem conncecten via terminal ein:

```
ccfg_cli set username@wan050=vodafone-vdsl.komplett/ab5175123456
ccfg_cli set password@wan050=geheimeskennwort
ccfg_cli set vlan_id@wan050=7
ccfg_cli set ivr_mode@bootstrap=2
ccfg_cli set arcor_pinConf@bootstrap=1
ccfg_cli set arcor_customer@bootstrap=1
ccfg_cli set keep_in_act@bootstrap=0
ccfg_cli set FirstUseDate@tr69=2015-05-24T01:07:49
ccfg_cli commitcfg

```

danke schon mal

**Comment by majuss** [comment]
Warum benutzt fu über Vodafone nicht deinen MIC? Wie sieht deine komplette Verkabelung aus? Woher weißt du, wie der Usename eingegeben werden muss, gibt Vodafone nicht nur den MIC raus?

**Comment by basiokan** [comment]
Hi ich habe eine Businenssanschluss - da gibt es nur den Usernamen / Kennwort 
- an meiner vorliegenden Fritzbox geht es damit ohne probleme

**Comment by majuss** [comment]
Ich schätze die Business Anschlüsse setzen noch ein paar andere Settings voraus. Welchen Vertrag konkret? Ist er mit einer festen IP? Ich würde einfach openWrt ausprobieren.

**Comment by majuss** [comment]
Irgendwelche Neuigkeiten?
