### ISSUE TITLE
Sip capability of openWrt 

### ISSUE THREAD

**Issue by mardosas** [majuss/easybox904#39]
Hello,

Is there a chance and are you planning to make the sip phone working?

Unfortunately, without sip the openWRT solution is not an option in my case. 

Best regards,

-Mardas

**Comment by majuss** [comment]
Just try it out and let us now what is happening. As far as I know, nobody ever tried it.

**Comment by majuss** [comment]
And did you tried SIP?

**Comment by majuss** [comment]
So did you have the chance to test it?
