### ISSUE TITLE
No outgoing calls

### ISSUE THREAD

**Issue by gruessung** [majuss/easybox904#4]
Hello, i follow the easy instructions for Deutsche Telekom. I'm able to recieve calls but it's not possible to do an outgoing call.
Do you have any idea why?

**Comment by majuss** [comment]
Hm it works for me also with Deutsche Telekom. Please review all of your parameters, maybe you god a digit wrong etc.

**Comment by gruessung** [comment]
Hab alles kontrolliert. Passt. Geht aber leider nicht.
Bekomme zwar ein Freizeichen, aber sobald er wählt tutet es ohne Ende.

**Comment by majuss** [comment]
Hast du mal die Home Talk app probiert? Poste bitte in welchem Format du deine Credentials eingetragen hast. Areacode ist nur die lokale Vorwahl also zB. 030 nichts mit +49 usw..

**Comment by majuss** [comment]
Irgendwelche News zu deinem Problem? Konntest du es klären?

**Comment by gruessung** [comment]
Ja, konnte es klären. Lag an einer selbst verlängerten TAE Dose... ^^
