### ISSUE TITLE
guide for openWrt installation - Erfahrungen/Probleme/Hinweise

### ISSUE THREAD

**Issue by Laerri** [majuss/easybox904#40]
Hallo majuss,

erstmal ein großes Dankeschön für deine Anleitungen. Damit konnte ich die EasyBox letztes Jahr mit O2 weiterverwenden und habe mich jetzt mit openWRT ausprobiert. Vorab: Ich bin wahrlich kein Linux-Experte, daher hatte ich an einigen Stellen so meine Probleme (habe es allerdings geschafft mich bis Punkt 18 durchzubeißen), daher hier ein paar Hinweise, die Deinen Guide vielleicht noch ein bisschen besser für Anfänger nachvollziehbar machen. Ich habe wie empfohlen einen Ubuntu Live-Stick benutzt, allerdings nicht alle Probleme direkt protokolliert, weshalb ich manches hier nur frei wiedergeben kann (vielleicht hilft es ja trotzdem - hab mich extra dafür bei GitHub angemeldet):

Allgemein: ich hatte ein paar Probleme mit Ordnerberechtigungen. Am Ende habe ich alles unter "/tmp" gemacht.

zu 4. Hier kam als Ausgabe, dass p7zip-full nicht gefunden werden kann, mit der Empfehlung, ein Kommando zum generellen Update einzugeben - gesagt, getan.

zu 6. "make tools" hat zunächst nicht funktioniert. Ich bin dem Tipp aus der Terminalausgabe gefolgt, indem ich den Ordner "freetz-devel" nochmal gelöscht und den Befehl "umask0022" eingegeben hatte, bevor ich "git clone https://github.com/Freetz/freetz.git freetz-devel" erneut ausgeführt habe. Danach hat "make tools" funktioniert.

zu 7. check - Version "FRITZ.Box_7490.113.07.01.image"

zu 8. "7z e Downloads/FRITZ.Box_7490.*.image -r filesystem.image" - hat erst geklappt, nachdem ich die Pfade angepasst und anstatt "FRITZ.Box_7490.*.image -r filesystem.image" den Dateinamen der Quelldatei ("FRITZ.Box_7490.113.07.01.image") ausgeschrieben hatte.
"7z e filesystem.image filesystem_core.squashfs" - hat nicht geklappt, Fehlermeldung: "Error: Can not open file as archive" - Ich habe dann die "FRITZ.Box_7490.113.07.01.image" unter Windows mit 7zip geöffnet, die Datei "filesystem_core.squashfs" extrahiert, mittels USB-Stick auf den Linux-Rechner gebracht und weiterbearbeitet.
Das anschließende Patchen war kein Problem, allerdings gab es hier keine Bestätigung. **Ist das normal?**

zu 18. Ich erhalte den Hinweis "-ash: nano: not found
Außerhalb der SSH-verbindung öffnet sich der Texteditor mit dem Befehl "nano". Auch nach einem Reboot des Routers, funktionierte es nicht. **Hier weiß ich jetzt wirklich nicht mehr weiter. Könntest Du mir hierbei helfen?**
**Edit:** Ich habe die datei network jetzt runtergeladen mit "scp root@192.168.1.1:/etc/config/network network", lokal mit einem Editor bearbeitet und anschließend mit "scp network root@192.168.1.1:/etc/config/network" wieder hochgeladen.
Ich habe meine Anmeldedaten eingegeben wie beschrieben (allerdings von O2), aber es wird keine Verbindung hergestellt (es wird auch nach zehn Minuten noch keine WAN-IP im Display angezeigt. **Muss für vDSL (bei O2) eine andere Konfiguration gemacht werden?**

Darüber hinaus hätte ich noch die Frage, wie ich den Router (WLAN, DSL etc.) jetzt einrichte. Du schreibst in einem anderen Issue, das müsse man auch über SSH machen. **Gibt es hierfür eine Anleitung?**

Riesendank nochmal!

Gruß,

Lärri

**Comment by majuss** [comment]
Wow danke für dein Feedback! Deine Punkte werden spätestens im Juni eingearbeitet wenn ich Zeit dafür finde. Vielleicht ist `nano` gar nicht bei openWrt dabie, kann ich dir grad gar nicht mehr sagen :D Verwende bitte `vi/vim`. Du Steuerung des Editors findest du bei Google.

Die VDSL Konfiguration ist Schritt 18. Wie genau der O2 Kram eingegeben werden muss, kannst du anderen Issues entnehmen (https://github.com/majuss/easybox904/issues/38 oder auch andere geschlossene).

WLAN config findest du hier: https://openwrt.org/docs/guide-user/network/wifi/basic

**Comment by majuss** [comment]
all comments were merged
