### ISSUE TITLE
DSL Speed

### ISSUE THREAD

**Issue by homerograco** [majuss/easybox904#41]
Hi again!

I decided to give OpenWRT a try. I followed your steps and everything was fine up to the end (the only hiccup was that the OpenWRT image has no `nano` and I used `vi` instead), thanks a lot for the tutorial!
 
I have one small issue though, my modem seems to be stuck with legacy DSL speeds. I performed various tests and it never goes above 19Mbps down / 1.5Mbps up. I decided to inspect `etc/config/networks` and noticed that the `dsl` config session has `annex 'a'` and `mode 'av'` which to me looks like ADSL (and would explain why the speed is low). I am not an expert tho, and don't know if this explains the speeds.

Would you know which values I should put there to enable full VDSL? I have a 50Mbps subscription and want to use it to its full potential.

Thanks a lot!

**Comment by majuss** [comment]
It sounds like the modem firmware was not loaded correctly and openWrt has fallen back to the slow integrated. Can you please show me the config line for the firmware file? Are you sure the firmware is in place?

Another problem is: When the DSLAM is measuring to many problems with your DSL-connection, it slows down the speed so it's save and without errors. Over 3 days the DSLAM will speed up the connection.

**Comment by homerograco** [comment]
I am not home now, but later I can give you more details.

Just for information, I remember checking `lib/firmware` and noticed a `lantiqxxxx-a` file and a `a-to-b-patch` one. I thought that was a bit funny because I expected that main firmware file to be `lantiqxxx-b` ...but anyway, not sure if this helps. I will check everything once I am home.

Thanks

**Comment by majuss** [comment]
`scp freetz-devel/squashfs-root/lib/modules/dsp_vr9/release-vr9-B-dsl.bin root@192.168.1.1:/lib/fw.bin`

This command should create a file called: `fw.bin` if it's not in place you have to copy it over again.

**Comment by homerograco** [comment]
Alright, will check this! Thanks!

**Comment by homerograco** [comment]
so... I performed the whole installation and made sure `fw.bin`is placed at `/lib` but still my connection is limited to legacy speeds.

In my `/etc/config` I have

```
config dsl 'dsl'                                                    
        option annex 'a'                                            
        option tone 'av'                                            
```

and `/lib/firmware` has

```
iNIC
ifx_bbd_fxs.bin
ifx_firmware.bin
lantiq-vrx200-a-to-b.bspatch
lantiq-vrx200-a.bin
rt2860.bin
rt3290.bin
voice_ar9_firmware.bin
vr9_bbd.bin
vr9_bbd_fxs.bin
xcpe_581816_580B11.LICENSE
xcpe_581816_580B11.bin
xcpe_581816_580B11_to_579906_574402.bspatch
`

shouldn't `fw.bin` be there too?

PS: I don't think there is a problem with the DSLAM because it was hitting 55Mbps just before I installed OpenWRT, so I am discarding this option.

**Comment by majuss** [comment]
Whoops the line to add the firmware path is actually missing in my guide :D just go onto the GUI and enter the path to `fw.bin` there.

**Comment by homerograco** [comment]
That was it ;)

Just add `option firmware '/lib/fw.bin'` to config dsl like this:

```
config dsl 'dsl'                                                    
        option annex 'a'                                            
        option tone 'av'
        option firmware '/lib/fw.bin'
```
and it is fixed.

(question now is: how to "unlock" even more speed? :P )

Thanks for your help, very appreciated!
