### ISSUE TITLE
Wifi support in your OpenWRT image

### ISSUE THREAD

**Issue by kaiomatico** [majuss/easybox904#42]
Hey, it's me again. After testing the latest OpenWrt image from the install guide you linked (2019-02-07) I found the Web Interface to be too slow / most of the times not working and also the display driver always crashing. So I reverted to your OpenWrt Image from your github resources folder which works much better. However I wanted to create a wlan to lan bridge (https://openwrt.org/docs/guide-user/network/wifi/relay_configuration#setup_with_cli) and got the following error: https://superuser.com/questions/958889/nl80211-not-foundhow-resolve-this-error-in-openwrt

Also the web interface is not able to scan for wifi networks, I guess the wifi driver is not included in your OpenWrt build? Could you please add the functionality to your OpenWrt image?

Thank you a lot in advance!

**Comment by majuss** [comment]
Please open an issue in Quallenauges Repo, I'am not the maintainer of the openWrt image :)

**Comment by kaiomatico** [comment]
Ah alright thank you. Quallenauge has not responded in the past, so I will probably just install OpenWrt on my raspberry pi then.
