### ISSUE TITLE
Ssh Connection refused

### ISSUE THREAD

**Issue by frodo3210** [majuss/easybox904#44]
Hey,

ich habe absolut keinen Plan von dem was hier so passiert, versuche es nur genauso wie beschrieben auszuführen.
Ich habe die Firmware wie beschrieben geupdatet, den Stick mit der Datei angeschlossen und neu gestartet. Wenn ich  über den in 4. beschriebenen Code in CMD versuche zuzugreifen, kommt sofort:
ssh: connect to host easy.box port 22: connection refused.
Leider komme ich da nicht weiter und auch bei den anderen Problemlösungen finde ich nichts für mich. Ich hoffe du kannst mir helfen.

VG

**Comment by majuss** [comment]
Wie hast du die Datei sesame.txt erstellt? Es liegt mit hoher Wahrscheinlichkeit an dem Stick und/oder der Datei.

**Comment by frodo3210** [comment]
hab den Stick als fat32 formatiert und die Datei über die Anleitung runtergeladen, als das nicht ging, hab ich sie über notepad++ erstellt, wie in der Anleitung beschrieben.

**Comment by ropasch** [comment]
Hi, 
ich hatte auch probleme SSH zum laufen zu bringen (vermutlich der Stick) 
Hab nach "3.Create..." (top guide, danke!) ein img erstellt und in `etc/init.d/dropbear` in start() ssh auf AlwaysOn gestellt. 

```
start()
{
	ccfg_cli set AlwaysOn@ssh=on
	ccfg_cli commitcfg
	/usr/sbin/arc_dropbear start
	test $? -ne 0 && return
	config_load "${NAME}"
	config_foreach dropbear_start dropbear
}
```
Ist vermutlich keine besonders schöne Lösung, aber SSH ist direkt beim ersten boot nach dem flashen verfügbar ohne sesame Stick.
Hier das modifizierte [fullimage_sshAlwaysOn.img](https://github.com/ropasch/easybox904/raw/master/resources/fullimage_sshAlwaysOn.img) 

Viele Grüße

**Comment by majuss** [comment]
Danke dir, wenn noch jemand anderes die Funktionalität bestätigen kann, werde ich es dauerhaft aufnehmen.

**Comment by dirk234** [comment]
Hallo,
tolle Anleitung, danke dafür! 
Mir ist es trotz fehlender Programmierkenntnisse gelungen, die Easybox für DSL mit einem neuen Telekom-Anschluss zum Laufen zu bringen. Telefon funktioniert aber leider noch nicht :-(  Evtl. liegt es daran, dass ich ein analoges / DECT-Telefon nutze? Sind hierfür weitere Einstellungen nötig? Könntest Du hier nochmal helfen, majuss? 
Das wäre super.

Das o.a. Problem mit der nicht herstellbaren SSH-Verbindung hatte ich übrigens auch. Bei mir hat es geholfen, das DSL-Kabel aus der Easybox zu ziehen u. den USB-Stick (nochmal) einzustecken.

Viele Grüße

**Comment by majuss** [comment]
Alle Einstellungen beim VOIP Abteil sollten eingetragen werden. Welcher Fehlercode erscheint denn?

**Comment by dirk234** [comment]
Hm. Es erscheint kein richtiger Fehlercode. In der graphischen Übersicht der angeschlossenen Geräte wird zwar ein Telefon aufgeführt, aber die Anzeige zeigt an "keine Geräte verbunden". Als Fehlercode erscheint 819 "Es liegt eine netzinterne Störung vor, welche die Funktion Ihres Anschlusses aber nicht beeinträchtigen dürfte".

**Comment by majuss** [comment]
819 ist ja auch interessant... Sicher das alles richtig verkabelt ist? Wie hast du die Tel-Nr eingegeben?

**Comment by dirk234** [comment]
Ich habe den Telefonstecker in der linken und in der mittleren Buchse probiert. Die Tel-Nr ist doch in dem Coding enthalten?! Die Vorwahl habe ich unter [AreaCode] erfasst, die Tel-Nr unter [PhoneNumber]. Wenn ich die Nummer von extern anrufe kommt eine Telekom-Mailbox mit der Ansage der Nummer.

**Comment by majuss** [comment]
Also Vorwahl hast du 030 für zB. Berlin genommen? Nicht +49 ;)

**Comment by dirk234** [comment]
ja genau. Die Städtevorwahl sozusagen.

**Comment by majuss** [comment]
Du kannst dir mal die geschlossenen Issues angucken ob du dort Hinweise findest die dir helfen... mir fällt grad auch nichts konkrete ein. Vlt. haut auch einer der Server nicht mehr hin etc.

**Comment by dirk234** [comment]
ok. Danke Dir. Ich gucke das mal durch.

**Comment by dirk234** [comment]
ich hatte gehofft, dass ich das falsche Telefon habe ;-)

**Comment by dirk234** [comment]
wenn das nicht klappt muss ich wohl doch noch eine Fritzbox kaufen.

**Comment by majuss** [comment]
Ich hab gar kein Festnetz mehr angeschlossen :) Hat ja heutzutage auch keinen Mehrwert mehr, wenn eigentlich eh so ziemlich jeder eine Flatrate hat.

**Comment by fpopic** [comment]
I had [04.16 open from vodafone ](https://www.vodafone.de/downloadarea/fullimage_AT904X-04.16.zip) and after I reverted back to AT904X-04.13 but now when trying ssh always getting

```shell
ssh -oKexAlgorithms=+diffie-hellman-group1-sha1  root@192.168.2.1 
Unable to negotiate with 192.168.2.1 port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss
```

Does this mean that usb drive and sesame.txt is not working? (I tried with 2 different  FAT32 usb drives).

**Comment by majuss** [comment]
Hm sesame seems to be working. Try bare ssh without specific keyalgorithm.

**Comment by fpopic** [comment]
@majuss 

```
Current Firmware Version:AT904X-04.13 (Linux 2.6.32.32 #1 Fri Mar 9 15:00:35 CST 2018)
``` 

``` 
$ ssh  root@192.168.2.1 -vv
OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022
debug1: Reading configuration data /home/fpopic/.ssh/config
debug1: /home/fpopic/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolve_canonicalize: hostname 192.168.2.1 is address
debug1: Connecting to 192.168.2.1 [192.168.2.1] port 22.
debug1: Connection established.
debug1: identity file /home/fpopic/.ssh/id_rsa type -1
debug1: identity file /home/fpopic/.ssh/id_rsa-cert type -1
debug1: identity file /home/fpopic/.ssh/id_ecdsa type -1
debug1: identity file /home/fpopic/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/fpopic/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/fpopic/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/fpopic/.ssh/id_ed25519 type -1
debug1: identity file /home/fpopic/.ssh/id_ed25519-cert type -1
debug1: identity file /home/fpopic/.ssh/id_ed25519_sk type -1
debug1: identity file /home/fpopic/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/fpopic/.ssh/id_xmss type -1
debug1: identity file /home/fpopic/.ssh/id_xmss-cert type -1
debug1: identity file /home/fpopic/.ssh/id_dsa type -1
debug1: identity file /home/fpopic/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
debug1: Remote protocol version 2.0, remote software version dropbear_2014.63
debug1: compat_banner: no match: dropbear_2014.63
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 192.168.2.1:22 as 'root'
debug1: load_hostkeys: fopen /home/fpopic/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,kexguess2@matt.ucc.asn.au
debug2: host key algorithms: ssh-rsa,ssh-dss
debug2: ciphers ctos: aes128-ctr,3des-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes256-cbc
debug2: ciphers stoc: aes128-ctr,3des-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes256-cbc
debug2: MACs ctos: hmac-sha1,hmac-md5
debug2: MACs stoc: hmac-sha1,hmac-md5
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: (no match)
Unable to negotiate with 192.168.2.1 port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss

```

**Comment by majuss** [comment]
Try something like this: ssh -oHostKeyAlgorithms=+ssh-dss root@192.168.2.1

**Comment by fpopic** [comment]
Thank you, seems my known hosts files were old

```shell
ssh -oHostKeyAlgorithms=+ssh-dss root@192.168.2.1  
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the DSA key sent by the remote host is
SHA256:fKG+Ht5EFEe4PswvEr895G5htVJGKsrCEqCyEAUdaxQ.
Please contact your system administrator.
Add correct host key in /home/fpopic/.ssh/known_hosts to get rid of this message.
Offending RSA key in /home/fpopic/.ssh/known_hosts:13
  remove with:
  ssh-keygen -f "/home/fpopic/.ssh/known_hosts" -R "192.168.2.1"
Host key for 192.168.2.1 has changed and you have requested strict checking.
Host key verification failed.

``` 

```shell
  ssh-keygen -f "/home/fpopic/.ssh/known_hosts" -R "192.168.2.1"
```

solved the issue.
