### ISSUE TITLE
NetAachen configuration

### ISSUE THREAD

**Issue by iCarletto** [majuss/easybox904#47]
Hi there,

I've just relocated and my previous FritzBox cable doesn't work here. I'm trying to use my old Vodafone easyBox 904 but I'm not sure how to configure the VDSL section for NetAachen.

The only information that I received from the ISP is:

Benutzername:   nc-xxxxx
Password:   YYYYYY
Registriernummer: YYYYYYZZZZZZZZZZZZZZ

I tried both:

ccfg_cli set username@wan050=nc-xxxxx#0001@NetAachen.de

and without #0001 but it doesn't work.

Any help on how to configure it for internet only (no phone) would be appreciated :)

**Comment by majuss** [comment]
I would throw away the: #0001 completely. You should look into older issues where people successfully configured everything for for example O2 and such.

**Comment by iCarletto** [comment]
I already had a look at the O2 example but there's no useful info there. I have some doubts:
Do I have to configure both ADSL and VDSL?
Is the username for NetAachen in the form  nc-xxxxx@NetAachen.de?
Are there other important network parameters to be set apart from username and password?

**Comment by majuss** [comment]
All common important parameters are described in my guide. The VLAN ID is also quite important maybe you can ask netAachen about it.
