### ISSUE TITLE
EasyBox kann nach Firmware flashen nicht mehr starten

### ISSUE THREAD

**Issue by InfernoLalala** [majuss/easybox904#5]
Nach dem Übertragen des Firmware IMG auf die Easybox via TFTP Server bekomme ich folgende Fehlermeldung auf dem Router beim Neustarten (sowohl mit als auch ohne USB Stick):

"Ihre EasyBox konnte nicht gestartet werden. Um in den Wiederherstellungs-Modus zu gelangen, schalten Sie bitte die EasyBox erneut ein, während sie den Reset-Knopf für mindestens 10 Sekunden gedrückt halten."

Habe die Firmware mit dem PumpKIN TFTP Server übertragen, da der empfohlene von SolarWinds nicht gestartet werden konnte.
Das Firmware IMG habe ich auch nochmal neu heruntergeladen und geflasht mit dem selben Ergebnis.
Ist das zum Download angebotene IMG evt beschädigt oder liegt es an mir? ;D

**Comment by majuss** [comment]
Hey, am besten mal mit Linux machen. Windows ist nicht gerade gut dafür.

Lad das image einfach noch einmal herunter, bei mir gehts. Wenns nicht geht, erstell dir dein eigenes Image.

**Comment by InfernoLalala** [comment]
gleiches Problem mit dem unter Linux erstellten IMG.
Hab es aber wieder über Windows auf die EasyBox geladen weil beim laden des tftpd-hpa Pakets unter Linux irgendwas schief gelaufen ist und ich das Paket bis jetzt weder entfernen noch neu installieren konnte.

**Comment by majuss** [comment]
Okay sehr misteriös... Welche EasyBox ist es konkret? Poste bitte die genaue Modellnummer.

**Comment by InfernoLalala** [comment]
Gleiches Problem wenn ich die original Firmware nehme (https://www.vodafone.de/downloadarea/fullimage_AT904X-03.17.01.16.zip) und in fullimage.img umbenenne. Easybox hängt quasi in einem Bootloop. Vodafone logo erscheint, "der Startvorgang läuft, dies kann einige Minuten dauern" erscheint und dann wird der Bildschirm schwarz, erneut das Vodafone Logo...

Die Daten (auf der Rückseite des Routers) sind:
EasyBox 904 xDSL
HW Version: R01
FW Version: AT904X-03.07
Article No.: 00-20-0103

Ansonsten stehen noch Serial Number, IMEI und irgend ein Twonky Key drauf.
Falls die wichtig sind schreib ich die auch gern noch ab.

**Comment by majuss** [comment]
Also nur um es klar zu stellen:
- Du downloadest die originale Firmware, entpackst sie und benennst sie in fullimage.img um
- Dann kopierst du sie ins transferverzeichnis deines tftp-serves und überträgst sie erfolgreich(!) auf die EasyBox
Trotzdem hängt sie im Bootloop?!

Wenn das der Fall ist, stimmt entweder etwas nicht mit deinem tftp-server (nimm mal debian live nicht ubuntu etc.) oder du hast die EasyBox hardbricked, indem du es irgendwie geschafft hast die Recovery zu zerstören (halte ich für unwahrscheinlich).

**Comment by frrrrank** [comment]
Hi Majuss, ich habe exakt das gleiche Problem und auch alles versucht.

**Comment by majuss** [comment]
Also nur um es klar zu stellen:

• Du downloadest die *originale* Firmware, entpackst sie und benennst sie in fullimage.img um
• Dann kopierst du sie ins transferverzeichnis deines tftp-serves und überträgst sie erfolgreich(!) auf die EasyBox
Trotzdem hängt sie im Bootloop?!

Wenn das der Fall ist, stimmt entweder etwas nicht mit deinem tftp-server (nimm mal debian live nicht ubuntu etc.) oder du hast die EasyBox hardbricked, indem du es irgendwie geschafft hast die Recovery zu zerstören (halte ich für unwahrscheinlich).

**Comment by frrrrank** [comment]
Ja, hängt auch mit originaler Firmware - startet nach 3 Sekunden Ladenachricht ein paarmal neu und dann kommt eine Nachricht auf rotem Hintergrund, dass die Box nicht gestartet werden kann und wie man in den Wiederherstellungsmodus kommt. 

Ich habe die Firmware mit einem tftp-server auf Mac übertragen. Deine Empfehlung es mal debian live zu versuchen, habe ich noch nicht ausprobiert.

**Comment by majuss** [comment]
Der Mac hat ja einen build-in TFTP-Server. Hast du den verwendet? Der hat bisher bei mir auch immer funktioniert. Das custom image kann die recovery partition aber nicht beschädigen und ein flashen der originalen Firmware sollte **immer** zum Grundzustand führen.

**Comment by frrrrank** [comment]
Ja, habe den Mac built-in Server verwendet. Mit Ubuntu hat es nicht funktioniert, aber die Image Datei habe ich mit Ubuntu erstellt.

Sehe ich auch so, dass die originale Firmware zum Grundzustand führen sollte, ist aber nicht so und damit ist die Box nun wahrscheinlich unbrauchbar.

**Comment by majuss** [comment]
Ich würde noch einmal alles von vorn machen. Dh. alle tftp Verzeichnisse leer machen, alle images löschen und das originale von Vodafone downloaden und raufflashen. Viel mehr kann ich dazu auch nicht sagen. Ich habe meine EB auch öfters zerschossen, aber das originale Image hat immer funktioniert. Muss es eigentlich auch, denn die Recovery Partition wird durch den Flashvorgang überhaupt nicht beeinträchtigt.

**Comment by frrrrank** [comment]
Danke für Dein Feedback, aber die originale Firmware nutzt mir ja auch nichts, wenn ich die EB mit einem anderen Anbieter verwenden möchte.

**Comment by majuss** [comment]
Ja aber einfach nur um zu verifizieren, dass sie noch funktioniert. Das image hier bei Github, sollte immer funktionieren, ich hab es selbst etliche Male geflasht.

**Comment by majuss** [comment]
Wie siehts aus? Irgendwelche neuen Erkenntnisse? Hast du den neuen geschlossenen Issue gesehen?

**Comment by frrrrank** [comment]
Ist für mich nun uninteressant geworden, weil mein o2 Router dann endlich nach 3 Wochen kam. Aber cool, dass Du hier diese Anleitung veröffentlicht hast - hilft bestimmt noch einigen anderen. Danke und Grüße!
