### ISSUE TITLE
FW for LTE version

### ISSUE THREAD

**Issue by daniel1975937** [majuss/easybox904#54]
Hi, I got a easy box904 and 1st tried to update firmware, answer:
Die ausgewählte Datei ist keine gültige Firmware
after that of course no chance to take next steps, everything is ready, connection by lan and using windows 10
thx
Daniel

**Comment by majuss** [comment]
Please leave more information in your post. How did you tried to update the firmware?

**Comment by daniel1975937** [comment]
HI Majuss,
thanks a lot for your response.

like on your manual written :
https://github.com/majuss/easybox904/blob/master/guides/german.md
downloaded the firmware>the router (vodafone version) was reseted already
(bought on ebay for my O2 LTE card), >updated inside of adjustments the
firmware, the image was on my computer and uploaded successfuly to router
and after finishing the installation got the answer "wrong firmware".
what's wrong?

I found in internet a manual which use telnet connection (
https://router-kaufen.com/vodafone-easybox-904-lte-fuer-andere-provider-zugaenglich-machen/
)
the first 2 sections are interesting ( O2) maybe a solution as well?

by the way, when this firmware works, I can't update the firmware anymore,
correct?

thanks for your help!

Daniel

Am Fr., 31. Juli 2020 um 08:32 Uhr schrieb majuss <notifications@github.com

**Comment by majuss** [comment]
I think you have the LTE Box, please upload a photo of the sticker on the backside.

**Comment by daniel1975937** [comment]
Hi Majuss,
Indeed its a lte version a photo below.
Thx


majuss <notifications@github.com> schrieb am Do., 6. Aug. 2020, 10:02:

**Comment by majuss** [comment]
So it can't work with the LTE Version :) You need to create your own custom firmware see guide 3. If you're unsuccessful I will help you out.

**Comment by daniel1975937** [comment]
ok thanks, I will try :)

**Comment by Meins321** [comment]
Please report it back as many users have the lte version, Easybox 904 xDSL

**Comment by daniel1975937** [comment]
I solved this problem using following manual:
[https://router-kaufen.com/vodafone-easybox-904-lte-fuer-andere-provider-zugaenglich-machen/]
it works great wiht my  teleko card
cheers
Daniel

**Comment by majuss** [comment]
It should also work fine with this guide, just mind the config variables.
