### ISSUE TITLE
SSH Verbindung schlägt fehl

### ISSUE THREAD

**Issue by Cynja96** [majuss/easybox904#55]
Bei diesem Befehl:

ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 root@192.168.2.1

bekomme ich den Fehler

Connection refused

Habe ich vielleicht etwas vergessen zu machen?

**Comment by majuss** [comment]
Wie wurde der Stick erstellt? Wie lange hast du gewartet?

**Comment by Cynja96** [comment]
Ich hab die Textdatei runtergeladen und auf den Stick gezogen.
Stick eingesteckt und gewartet bis der Router gebootet hatte.
Danach ausprobiert, nochmal 10 Minuten gewartet und nochmal probiert.

**Comment by Cynja96** [comment]
Ich habe es gerade mit nem anderen USB Stick nochmal probiert und es hat funktioniert.
