### ISSUE TITLE
VDSL connected, but no IPv6 address

### ISSUE THREAD

**Issue by wolleric** [majuss/easybox904#59]
Hi @majuss,

thanks for the great guides! I am trying to get it to work with the VDSL50 connection of our local provider "htp", and the internet link is established ("Show Time"), but it does not obtain any WAN IP address.
The provider insists on using IPv6, could this be a issue?

**Comment by wolleric** [comment]
I should add that it is a "DS-lite" link, i.e. IPv6-only.

**Comment by majuss** [comment]
When you're connected via ssh run: `ccfg_cli showcfg` to look for ipv6 config entries.

**Comment by wolleric** [comment]
> When you're connected via ssh run: `ccfg_cli showcfg` to look for ipv6 config entries.

Here is what I believe to be the interesting part:

root@easy:~# ccfg_cli showcfg|grep -i ip6
[...other interfaces...]
ip6_enable@wan050 = 1
ip6_proto@wan050 = dhcp
ip6_addr@wan050 =
ip6_prefix@wan050 =
ip6_pfxlen@wan050 = 64
ip6_gateway@wan050 =
ip6_stateless@wan050 = 0
ip6_duid@wan050 =
ip6_duid_type@wan050 = 2
ip6_domain@wan050 =
ip6_sntp@wan050 =
ip6_dns@wan050 =
ip6_dns_primary@wan050 =
ip6_dns_secondary@wan050 =
ip6_lease@wan050 =
ip6_life@wan050 =
ip6_renew@wan050 =
ip6_rebind@wan050 =
ip6_delegate_prefix@wan050 =
ip6_delegate_pfxlen@wan050 =
ip6_changed@wan050 = 0
ip6_dhcp6c_rebind_instead_of_solicit@wan050 = 0
ip6_filter_cnt@wan050 = 0
ip6_filter_list@wan050 =
ip6_tunnel_type@wan050 = 0
ip6_tunnel_status@wan050 =
ip6_6rd_ifname@wan050 = 6rd
ip6_6rd_info@wan050 =
ip6_6rd_prefix@wan050 =
ip6_6rd_pfxlen@wan050 = 0
ip6_6rd_border_relay@wan050 =
ip6_6rd_v4mask@wan050 = 0
ip6_6to4_ifname@wan050 = 6to4
ip6_6to4_subnetid@wan050 = 0
ip6_6to4_border_relay@wan050 = 192.88.99.1
ip6_enable@system = 0
ip6_dns1@system =
ip6_dns2@system =
ip6_dhcp6c_prefix_mode@system = 0
ip6_dhcp6c_random_case@system = 0
ip6_dhcp6c_prefix_addr@system =
ip6_dhcp6c_prefix_length@system = 56
ip6_extra_sid@system =
ip6_pre_routing_prefix@system =
[...other interfaces...]

I have tried values 0-4 for "ip6_tunnel_type@wan050", but no effect. Next test will be "ip6_enable@system"...
Any suggestions?

**Comment by majuss** [comment]
Nope absolutely no clue. You would need someone with a Vodafone connection and their config dump regarding ipv6. The alternative would be openWrt if you don't need the fixed phone.

**Comment by wolleric** [comment]
I tried openWrt, just to test the DSL connection, but it says something like "ERROR: interface does not exist" in the WebUI. I checked twice that everything was done acc. to your tutorial...

**Comment by majuss** [comment]
Which version of owrt did you tried exactly?

**Comment by wolleric** [comment]
2019-02-07

**Comment by majuss** [comment]
owrt is under constant development, please see this wiki entry: https://openwrt.org/toh/astoria/arcadyan_astoria_easybox_904xdsl_r01 to install the latest owrt. You need a computer running Linux.

**Comment by majuss** [comment]
Give me a heads up, if you're not able to compile owrt.

**Comment by majuss** [comment]
@wolleric any news :)?

**Comment by wolleric** [comment]
@majuss Actually I gave up on that box. That linked OpenWRT version came without full IPv6 support, which is necessary in my case. I couldn't get the compilation to work, but it seemed anyway that IPv6 support would exceed the storage size of the box...

Used an old Fritz!Box now. Thanks for caring! :)
