### ISSUE TITLE
Keine Verbindung zur Box möglich

### ISSUE THREAD

**Issue by Smirre89** [majuss/easybox904#6]
Lieber Majuss, ich gebe es zu, ich bin absoluter Neuling bei Linux und stelle mich deshalb wohl ziemlich dumm an. Dies nur vorab, falls du dich wunderst, was ich für Fragen stelle.
Vorab: Die Firmware aufzuspielen hat gut geklappt, nun bin ich an dem Punkt angelangt, dass ich meine Telekomdaten eingeben will, aber die Box lässt mich über ssh einfach nicht rein. Egal, ob mit Debian oder unter Windows (CygWin64 oder Putty), stets kommt ein Access denied. Firewall ist natürlich down. Debian läuft in einer Virtualbox. Es wäre ganz wunderbar, wenn du mich unterstützen könntest. Vielen Dank auch, dass du dir die Mühe machst, die Kisten weiterhin am Laufen zu halten. Die würden ja sonst unter geplante Obsoleszenz fallen. Danke & Gruß, Smirre.

**Comment by majuss** [comment]
Hallo, alles kein Problem ich helfe gern :)
Als erstes ist zu beachten das der ssh-Server auf der EB bis zu 5 Minuten braucht bis er initialisiert ist, also ruhig ne Weile warten. Und natürlich das Kabel überprüfen ;)
Ansonsten hattest du einen USB-Stick dran mit dem "sesame.txt"? Das aktiviert den ssh-server erst auf der EB.

**Comment by Smirre89** [comment]
Hallo Majuss, danke für deine schnelle Antwort! Da man sich ja tatsächlich nie sicher sein kann, ob man irgendwas reingewurstet hat, habe ich alles nochmal neu gemacht. Leider mit dem gleichen Resultat: Connection refused. Ja, ich habe sogar sehr viel länger als fünf Minuten gewartet. Ja, das Kabel war dran, sonst wäre ich auch über 192.168.2.1 nicht reingekommen und hätte kein Passwort setzen können :)  Ja, ich hatte den USB-Stick mit "Sesame.txt" dran. Hat die EB aber offenbar nicht beeindruckt. Hast du noch Energie für Unterstützung, bevor ich Geld für eine eigentlich überflüssige Fritzbox ausgebe? Das wäre super!

**Comment by majuss** [comment]
Hänge bitte mal ein -vvv an den ssh Befehl: `ssh easy -vvv` Und poste den output hier. Wenn das alles nicht klappt versuch mal dir ein eigenes Image zu erstellen. War der Stick FAT 32 formatiert? Das sesamte.txt solltest du am besten mit Linux `touch` erstellen bzw. mit notepad++ nicht mit dem Windows Editor!

**Comment by Smirre89** [comment]
Alles klar, das teste ich mal. Und - erwischt - der sesame.txt-Datei war mit dem Windows Editor erstellt. Ich mache das jetzt mal komplett per Linux, so langsam bekomme ich ein Gefühl dafür. Gaaaanz langsam :) Ich melde mich, danke!

**Comment by Smirre89** [comment]
Lieber Majuss, so langsam kommen wir der Sache tatsächlich näher. Mit einer via Notepad++ erstellten sesame.txt-Datei funktioniert das Ganze schon mal unter ssh. So einfach war das also :) Bei mir heißt die Box übrigens Easy.box, daher hat das Easy auch nie funktionert. Was nicht checke ist das Einfügen von

Host easy (in meinem Fall dann wohl easy.box)
	Hostname 192.168.2.1
	User root
	KexAlgorithms diffie-hellman-group1-sha1

Via Putty fügt er die entsprechenden Algorythmen selbstständig zu, dann aber erkennt er mein Passwort  nicht. Ich probiere weiter!

**Comment by majuss** [comment]
Putty ist auch absolut nicht zu empfehlen, ein natives Linux ist die beste Wahl! (sieht du ja allein schon am .txt ;))

**Comment by Smirre89** [comment]
Ja, ist wohl wahr. Muss ich mir was einfallen lassen, da mein Toughbook enfach nicht Lubuntu vom USB-Stick starten will. Muss ich halt Partitionieren. Wird nicht langweilig :))

**Comment by majuss** [comment]
Versuchs am besten mit Debian:

Einfach das Programm `Rufus` (Windows) herunterladen und einen bootbaren Stick erstellen.

**Comment by Smirre89** [comment]
Ja, ist wohl wahr. Muss ich mir was einfallen lassen, da mein Toughbook enfach nicht Lubuntu vom USB-Stick starten will. Muss ich halt Partitionieren. Wird nicht langweilig :))

**Comment by Smirre89** [comment]
Zwei Tage herumdoktorn sind genug. Ich steige jetzt erst mal aus. Trotzdem danke!

**Comment by T-E-N** [comment]
> War der Stick FAT 32 formatiert?
> Das  sesame.txt [so wohl die erwartete Schreibweise?] solltest du am besten mit Linux touch erstellen
> bzw. mit notepad++ nicht mit dem Windows Editor!

In Größe von 0 Bytes sollte sich diese doch auch durch Rechtsklick und Anlage einer neuen Textdatei (ohne sie je mit einem Editor zu schreiben) im Stammverzeichnis des unter Windows angemeldeten USB-Sticks erstellen lassen?
