### ISSUE TITLE
ssh connection refused

### ISSUE THREAD

**Issue by lukasmatusiewicz** [majuss/easybox904#60]
Hi @majuss ,

firstly thank you for your afford to do this repo. I am trying to follow your easy guide and have stuck by the connection to root@192.168.2.1. If I am connected with the router by LAN cable I become error: ssh: connect to host 192.168.2.1 port 22: Connection refused. Are you using port 22 on this server? Is there everything right with openssh and so on? Or maybe I am doing something wrong. Thank you in advance!

**Comment by majuss** [comment]
Please see the already closed issues :) Oftentimes you need to wait longer.

**Comment by lukasmatusiewicz** [comment]
thank you. another stick helped.
