### ISSUE TITLE
Easybox verbindet sich nicht mit dem Internet

### ISSUE THREAD

**Issue by Keek09** [majuss/easybox904#7]
Es hat nun soweit alles funktioniert!

Ich habe auch bereits die Einwahldaten über SSH in die easybox eingetragen. Das Problem ist nun nur, das sich die easybox nicht mit dem Internet verbindet.

Ich würde gerne einen 50Mbit DSL Anschluss der Telekom nutzen. Besteht die Möglichkeit irgendwie zu prüfen, was hier noch nicht passt?

Vielen Dank im Voraus!!!

**Comment by majuss** [comment]
Bitte das beachten:
```
ccfg_cli set username@wan050=[Anschlusskennung][T-Onlinenummer]#0001@t-online.de
ccfg_cli set password@wan050=[Password]
ccfg_cli set vlan_id@wan050=7
```

Und die # nicht vergessen!

**Comment by Keek09** [comment]
Ich habe es bereits mit # eingegeben! Irgendwo stand jetzt, dass es bei einer 12stelligen T-online Nummer ohne Raute eingegeben werden muss!

Anschließend dann ein Reboot und den USB Stick abziehen?

**Comment by Keek09** [comment]
okay! Dann gebe ich es noch einmal mit raute ein! Und save durch "commitcfg", oder mit einem anderen Befehl!?

**Comment by majuss** [comment]
Nein mit commit ist schon richtig.

**Comment by Keek09** [comment]
Mhhh! Wenn ich das alles so mache und dann versuche eine Seite im Internet aufzurufen werde ich auf die Easybox (192.168.2.1) umgeleitet und es erscheint die Meldung "Keine Internetverbindung" - Sie haben keine Internetvebindung, da die EasyBox bisher nicht aktiviert wurde. Bitte klicken Sie auf Aktivieren um mit der Anmeldung Ihrer EasyBox zu beginnen!

**Comment by Keek09** [comment]
So, ich habe es gelöst! 😉 Es fehlte noch die Aktivierung aus der englischen Anleitung! Jetzt funzt es! Top! Vielen Dank für die Anleitung und die Hilfe!!!

**Comment by Keek09** [comment]
Leider zu früh gefreut! ;(

Für eine kurze Zeit hat es funktioniert und ich konnte auch einen Speedtest machen!

Nun erscheinen leider die Fehlercodes 812 und 814. Jetzt weiß ich leider auch nicht mehr weiter!

**Comment by majuss** [comment]
Ja du solltest die englische Anleitung beachten nicht die deutsche... Mach einfach alles noch einmal von vorn, mehr kann ich dir leider auch nicht helfen.

**Comment by majuss** [comment]
Ich habe die deutsche Anleitung aktualisiert, bitte um Rückmeldung.

**Comment by Keek09** [comment]
So, jetzt passt alles! Internet läuft! Vielen Dank für die Unterstützung! Anscheinend hat der TFTPD des Rechners noch irgendwie dazwischen gefunkt! Jetzt läuft die Box ohne Fehler und das Inet ist dauerhaft vorhanden! Danke!!!

**Comment by majuss** [comment]
Super!

**Comment by T-E-N** [comment]
> die englische Anleitung beachten nicht die deutsche

Darf in deren Punkt 8. unter https://github.com/majuss/easybox904/blob/master/README.md wirklich schon stehen "connect via ssh to the Box" - oder kommt das erst nach (ssh-keygen und?) Anlegen der ~/.ssh/config ?

Wird zusätzlich folgende Zeile benötigt?
IdentityFile ~/.ssh/id_rsa
Diese ist unter "Schritt 3." der deutschen langen https://github.com/majuss/easybox904/blob/master/Anleitung_deutsch.mdown aufgeführt,
die aber nicht sagt, wann der USB-Sticks wieder (dauerhaft?) entfernt werden sollte
(sondern nur: "neustarten und die Einrichtung, bis auf das Kennwort, überspringen" womit wohl "Setup abbrechen" über das LCD-Menü direkt an der 904 gemeint ist?).

**Comment by majuss** [comment]
Schritt 8 ist ein bisschen unglücklich formuliert, da hast du Recht!

Die Zeile ist nicht notwendig.

Okay danke, werde ich ausbessern!

**Comment by Eshatos** [comment]
Hallo, 
ich habe ein ähnliches Problem, habe meinen Telekomanschluss über ssh als VDSL konfiguriert und auch den Punkt "Activation" nicht vergessen. Trotzdem bekomme ich die Fehlercodes 812 und 814...
Weis jemand vielleicht Rat?
