### ISSUE TITLE
Can't install the OpenFirmware

### ISSUE THREAD

**Issue by DrChaoss** [majuss/easybox904#8]
Hi, Thank you very much for this intersting project! Unfortunately I was unable to install the Firmware, after download and apparently successful falshing the router does not restart (Easy box konnte nicht gestartet werden) and ask for the "Wiederherstellungsmodus". From there I am stuck. Tried it from MAcOS and Windows 10, with different USB Sticks...

**Comment by majuss** [comment]
Which TFTP Server did you tried?

The USB-Stick is not crucial for booting, you can try booting it without a stick. If the stick is connected the ssh-server will start.

**Comment by Sebastian06** [comment]
Hi majuss,
ich habe das selbe Problem, wie hier und auch in bereits geschlossenen Issues beschrieben:
Nachdem bzw. seitdem ich das Firmware-Image geflasht habe, hängt die Easybox im Bootloop. Das gilt sowohl für Tftp-Server auf Ubuntu, Windows oder Debian-Live sowie deinem geänderten Image und dem Original von der Vodafone-Seite.
Falls es noch Lösungsmöglichkeiten gibt, wäre ich natürlich erfreut. Ansonsten würde ich vielleicht mit ins Readme packen, dass die Easybox im Anschluss unbrauchbar werden kann.
Viele Grüße

**Comment by majuss** [comment]
Ja das sollte dann vielleicht mit rein... trotzdem gibt es mir zu denken, wie das passieren kann. Denn wie schon beschrieben wird ja die Recovery Partition nicht verändert. Gibt es vielleicht die Möglichkeit, dass du mir das halbkaputte Teil per Post schickst?

**Comment by Sebastian06** [comment]
Ich schau mal wie hoch die Versandkosten wären. Wenn sich das im Rahmen hält, mache ich das gerne.

**Comment by majuss** [comment]
DHL Päckchen wäre 3,89 €. Wenn ich das Teil wieder hinbekomme, bekommst du sie natürlich auch wieder :D!

**Comment by Sebastian06** [comment]
Ich schau mal was mich jetzt der nächste Router kosten wird und gebe dir dann Bescheid (bin armer Student :D).
Btw: Wo wohnst du denn, wenn ich fragen darf? Vielleicht bin ich ja zufällig demnächst in der Gegend :)

**Comment by DrChaoss** [comment]
Ich habe es mit macos und Windows (opentftp) versucht. Originalfirmware habe Ich noch nicht probiert, ich nehme an die finde ich im Netz? Hast du selbst schon  mal die img vom Download installiert, oder hast du immer eine lokale Datei probiert? Ich hatte das Problem schon mal bei einem anderen github Projekt... Allerdings war dann die datei immer defekt, hier wird ja erfolgreich geflashed. Sorry übrigens, die closed habe ich einfach übersehen...

**Comment by majuss** [comment]
Den link zur originalen Firmware findest du auch direkt im Guide.

Ich wohne in der Nähe von Berlin.

**Comment by Sebastian06** [comment]
Ja gut, das ist leider ein wenig weit weg.
Die bin-Datei kann ich ja einfach in eine img-Datei umwandeln, richtig?

**Comment by majuss** [comment]
Ja einfach umbenennen.

**Comment by DrChaoss** [comment]
Original Firmware geflasht mit dem gleichen Ergebnis. FTFTP lief auf MacOS...

**Comment by DrChaoss** [comment]
Ich könnte Dir die Box schicken. Ich wollte die ohnehin für meinen Nachbarn, ich habe derzeit den O2 Zwangsrouter...

**Comment by majuss** [comment]
Cool! Schreib mir ne email an: ich@majuss.de. Dann bekommst du meine Adresse etc.

**Comment by Sebastian06** [comment]
Dann brauche ich das ja nicht mehr zu machen :).
Bin dann mal gespannt, ob du eine Lösung findest! :)

**Comment by lyn1337** [comment]
Falls Bedarf besteht, gebe ich meine auch ab.

**Comment by majuss** [comment]
Ja es besteht definitiv Bedarf! Bitte schreib mir doch eine email. Bei der vom DrChaos komme ich nicht in den seriellen Modus. Vielleicht habe ich mit deiner mehr Glück.

**Comment by lyn1337** [comment]
Erledigt! Vielleicht im spam...

**Comment by jamespresley** [comment]
Hallo @majuss!

Ich habe das selbe Problem. Die Easybox hängt nun im Bootloop. :(
Hast du schon eine Lösung?

**Comment by majuss** [comment]
Nope noch nicht. Aber ich arbeite daran. Könntest du mir den genauen Vorgang schildern? Vlt. einen alten Browser zum downloaden verwendet? Welchen TFTP server? etc. Denn eigentlich kann die recovery Partition nicht zerflasht werden...

**Comment by jamespresley** [comment]
Ich hänge bei Schritt 5 deiner Anleitung. 
Nach dem Neustart bootet die Box immer wieder und kommt dann zur Fehlermeldung (Wiederherstellung). 

Ich habe Tftpd32 als Tftp-server verwendet, da sich der Server bei SolarWinds unter Windows 10 nicht starten ließ.

**Comment by majuss** [comment]
Dann liegt es wohl an Windows + TFTP-Server. Habe bisher nur Debian und macOS verwendet und nie Probleme gehabt...

**Comment by lyn1337** [comment]
Mit tftpd aus Debian hat es definitiv geklappt.

**Comment by Sebastian06** [comment]
Mit dem tftp auf Ubuntu nicht.. Habe danach noch Windows und Debian probiert, aber da war es vermutlich sowieso schon zu spät..

**Comment by majuss** [comment]
Interessante Beobachtungen... ich werde den Guide eventuell in naher Zukunft einfach auf Debian und macOS beschränken. Ubuntu ist ja auch schon viel zu aufgebläht.

**Comment by jamespresley** [comment]
Werde es dann vielleicht nochmals mit Linux versuchen, wenn es nicht schon zu spät ist.

Gibt es ansonsten eine Möglichkeit, die Easybox wieder normal zum Laufen zu bekommen, wenn wie du sagst die Recovery-Partition nicht "zerflasht" werden kann?

**Comment by majuss** [comment]
Ja gibt eine Möglichkeit. Du musst sie per serieller Konsole anschließen, aber ich arbeite gerade daran den genauen Vorgang KOMPLETT zu dokumentieren, also musst du dich noch gedulden.

**Comment by jamespresley** [comment]
Ok. Danke bereits im Vorfeld, @majuss !

Vielleicht finden wir ja auch noch eine Lösung ...

**Comment by majuss** [comment]
Der Debricking guide ist ja sehr rudimentär im Openwrt wiki dokumentiert... ich fülle jetzt die Lücken mit trial and error. Das kann noch einen Monat dauern oder eine Woche, oder ich bekomme es überhaupt nicht hin. Aber ihr könnt es gern selbst versuchen ;) Eine USB serielle Konsole kostet 3€.

**Comment by lyn1337** [comment]
Ich dachte ein reflash hätte da schon gereicht.

**Comment by jamespresley** [comment]
So, nun via Linux ein neuer Versuch. Selbes Problem wie bisher, auch mit der Datei von Vodafone.

Ist schon jemand weiter gekommen?
Liegt es vielleicht an dem Vodafone Bootloader auf der Box?

**Comment by majuss** [comment]
Ja es liegt an den Boot-Parametern von u-boot. Deshalb muss u-boot neu geflasht werden. Aber das ist nur mit serieller Konsole möglich: https://wiki.openwrt.org/inbox/arcadyanastoria/arcadyan_astoria_easybox_904xdsl_r01#debricking

**Comment by shukari** [comment]
Habs per Windows mit PupKIN TFTP versucht und hänge auch in der Bootloop... jetzt muss ich wohl einen neuen Router kaufen... ggf. über den Guide nochmal schreiben das das mehr als gefährlich ist deine Anleitung zu machen ;D

**Comment by majuss** [comment]
Ich habe eher github in Verdacht. Irgendwie geht das Image beim Download kaputt oder so. Noch konnte ich es nicht eingrenzen. Du hättest dir doch eh nen neuen Router kaufen müssen xD

**Comment by majuss** [comment]
Hab noch ne Warnung eingefügt das man es nicht unter Windows machen sollte. Bisher haben glaube ich nur die User mit Windows Probleme gehabt...

**Comment by lyn1337** [comment]
keine Prüfsumme...?

**Comment by majuss** [comment]
Hab grad keine funktionierende EB mit der ich ein Image testen könnte :D

**Comment by lyn1337** [comment]
kek

dennoch, ich verstehe zwar nicht viel von dem tftp Protokoll, aber halte die Probleme i.V.m. NT für sonderbar.

**Comment by majuss** [comment]
Ich werde demnächst nochmal eins selber bauen und mit Checksumme hochladen.

**Comment by hleg** [comment]
ich hatte kein Problem mit dem Bootloop, aber  Schritt 9 macht Probleme:
"unable to negotiate with 192.168.2.1 port 22: no matching key exchange methode found. Thier offer: diffie-hellman-group1-sha1"
Ubuntu & Debian geben die gleiche Fehlermeldung raus

**Comment by majuss** [comment]
```Host easy
	Hostname 192.168.2.1
	User root
	KexAlgorithms diffie-hellman-group1-sha1```

Ist nicht optional, musst du benutzen

**Comment by majuss** [comment]
@hleg also hat das fertige image hier von github funktioniert?

**Comment by majuss** [comment]
Debricking guide kommt gleich online, damit geht jede Box wieder, es ist nicht möglich sie komplett zu zerstören.

**Comment by majuss** [comment]
Debricking online
