### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by DaViAC** [majuss/easybox904#9]
Hi,

auch wenn ich glaube, dass es weniger mit dem Image zusammenhängt, ich kann mich einfach nicht mit dem Router verbinden.

Ich bin der Anleitung buchstabengetreu gefolgt und unter Ubuntu 16.04 LTS ein eigenes Image erstellt, nachdem ich mit dem Image hier von Github immer ein "connection refused" bekommen habe. Ich bin den Prozess inzwischen bestimmt mehr als dreimal durchgegangen.

- neuen SSH-Key erstellt, public liegt unter ~/.ssh/id_rsa.pub
- neues Image nach Anleitung erstellt
-- SSH-Key um Fehler zu vermeiden per "cat ~/.ssh/id_rsa.pub >> config/cert/authorized_keys" kopiert und danach die Datei mit "less" ausgegeben (Vorher-/Nachher-Vergleich)
- Image auf die Box gespielt, mit USB-Stick neugestartet und Passwort auf dem Web-Frontend gesetzt, nochmaliger Neustart der Box (Power Off-On)

Auch beim letzten Schritt bin ich mehrere Versuche durchgegangen. Mit und ohne USB-Stick, da gibt es Unterschiede zum Quick Guide und der deutschen Übersetzung. Egal, was ich mache, ich bekomme ein "Permission denied". Wenn ich "ssh easy" eingebe, bekomme ich das gleiche Ergebnis, die ~/.ssh/config ist entsprechend angepasst.

```
ssh root@192.168.2.1 -vv
OpenSSH_7.2p2 Ubuntu-4ubuntu2.2, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /home/user/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "192.168.2.1" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 192.168.2.1 [192.168.2.1] port 22.
debug1: Connection established.
debug1: identity file /home/user/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/user/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/user/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/user/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/user/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/user/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/user/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/user/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
debug1: Remote protocol version 2.0, remote software version dropbear_0.52
debug1: no match: dropbear_0.52
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 192.168.2.1:22 as 'root'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,ext-info-c
debug2: host key algorithms: ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: diffie-hellman-group1-sha1
debug2: host key algorithms: ssh-rsa,ssh-dss
debug2: ciphers ctos: aes128-ctr,3des-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes256-cbc,twofish256-cbc,twofish-cbc,twofish128-cbc,blowfish-cbc
debug2: ciphers stoc: aes128-ctr,3des-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes256-cbc,twofish256-cbc,twofish-cbc,twofish128-cbc,blowfish-cbc
debug2: MACs ctos: hmac-sha1-96,hmac-sha1,hmac-md5
debug2: MACs stoc: hmac-sha1-96,hmac-sha1,hmac-md5
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: diffie-hellman-group1-sha1
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1 compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1 compression: none
debug1: sending SSH2_MSG_KEXDH_INIT
debug2: bits set: 529/1024
debug1: expecting SSH2_MSG_KEXDH_REPLY
debug1: Server host key: ssh-rsa SHA256:djJ6Z4yKdHDWAwfp172Rkml/rHl4WFZfzV5/9KgGB8M
debug1: Host '192.168.2.1' is known and matches the RSA host key.
debug1: Found key in /home/user/.ssh/known_hosts:1
debug2: bits set: 506/1024
debug2: set_newkeys: mode 1
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS received
debug2: key: /home/user/.ssh/id_rsa (0x5581a9733bf0), agent
debug2: key: /home/user/.ssh/id_dsa ((nil))
debug2: key: /home/user/.ssh/id_ecdsa ((nil))
debug2: key: /home/user/.ssh/id_ed25519 ((nil))
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/user/.ssh/id_rsa
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey
debug1: Trying private key: /home/user/.ssh/id_dsa
debug1: Trying private key: /home/user/.ssh/id_ecdsa
debug1: Trying private key: /home/user/.ssh/id_ed25519
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey).
```
Die Ornderangaben habe ich etwas angepasst: user = mein Username auf der VM

Eine Anpassung musste ich noch vornehmen, weil ich sonst in das Problem mit dem Key-Exchange gelaufen bin:

In /etc/ssh/ssh_config habe ich die Zeile "KexAlgorithms=+diffie-hellman-group1-sha1" hinzugefügt und die VM einmal neugestartet.

Wäre cool, wenn mal jemand drüberschauen würde, ich sehe den Wald vor lauter Bäumen nicht mehr. ;)

**Comment by majuss** [comment]
Warum eine VM? Probier es mal mit Live Linux und ohne Key. Der SSH-key ist eh nur optional und funktioniert gar nicht. Ich habe wie schon beschrieben leider keine EB mehr um alles nachzuvollziehen. Wenn Jemand seine funktionierende Box spenden würde, könnte ich den Guide neu schreiben und besser testen. In der jetzigen Situation müssen alle darauf warten, bis ich eine der "defekten" wieder hinbekomme.

**Comment by DaViAC** [comment]
Moinsen,

zu 1) Das 16.04 live Linux lässt keine Updates zu apt-get update wirft die Fehlermeldung, dass die alte DB nicht verschoben/gelöscht werden kann und bricht ab. Ohne das Update lässt sich aber nicht alle Pakete für ein eigenes Image installieren. Außerdem habe ich quasi immer eine "frische" Linux-VM bei mir auf dem Laptop. ;) Den USB-Stick bzw. die sesame.txt habe ich aber so erstellt

SSH-Verzeichnis gelöscht, dem Host vertraut: gleicher Fehler
SSH-Verzeichnis gelöscht, noch einmal das Image von Github probiert: gleicher Fehler
SSH-Verzeichnis gelöscht, ein neues Image ohne SSH Key erstellt: gleicher Fehler
Mit dem live Linux den USB-Stick neu erstellt (touch sesame.txt), Rest wie oben: gleicher Fehler

Per Stoppuhr/Timer habe ich teilweise bis zu zehn Minuten gewartet, das sollte also auch kein Fehlergrund sein.

**Comment by majuss** [comment]
Versuch mal nen anderen Stick, es liegt auf jedenfall daran, dass die EB nicht das sesame.txt frisst.

**Comment by DaViAC** [comment]
Hiho!

Sorry für das späte Update, war beruflich arg eingespannt. Leider ist das Problem immer noch nicht gelöst. Ich bin aber auch nicht großartig zum Probieren gekommen. Da ich nur mindestens 8GB  große USB-Sticks habe, habe ich einfach mal so rumprobiert, aber leider immer mit dem gleichen Ergebnis. Mit welcher Distro hast du denn das custom Fullimage gebaut, vielleicht stellt sich Ubuntu auch einfach nur an, wie gesagt 16.04 Server LTS. Vielleicht probier ich es mal mit nem 14.04 oder nem Debian...

In diesem Sinne
Da

**Comment by majuss** [comment]
Habe immer Raspbian also ein Debian verwendet. Ich kann mich auch wage erinnern, dass ich das selbe Problem hatte, hab aber nie eine zuverlässige Lösung finden können, es hatte dann einfach immer funktioniert. Du solltest auf jeden Fall mit dem Stick rumprobieren, dran lassen, neustart, nach 5 Minuten abziehen etc. pp.

**Comment by majuss** [comment]
Also ich konnte alles reproduzieren. Permission denied bekommst du NUR wenn du noch den Stick drin hast!!! Zieh ihn raus, EB restart, und dann nach 3 Minuten ssh versuchen, geht 100%.

**Comment by T-E-N** [comment]
> Permission denied bekommst du NUR wenn du noch den Stick drin hast!!!
> Zieh ihn raus, EB restart, und dann nach 3 Minuten ssh versuchen, geht 100%.

In den Anleitungen beider Sprachen kommt noch nicht klar und widerspruchsfrei rüber, wann der USB-Stick stecken und wann genau er wieder entfernt werden muss (bzw. welche Schritte zwingend zu wiederholen sind, wenn sesame.txt nicht erkannt wurde).
Vgl. die geschlossenen aber noch nicht abschließend kommentierten https://github.com/majuss/easybox904/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc ...

Um Bricks & Probleme nach Reboot zu vermeiden, könnte für die vielen Ubuntus & Derivate ein Hinweis helfen auf...
https://help.ubuntu.com/community/NetworkManager#Stopping_and_Disabling_NetworkManager
...damit dieser nicht automagisch dazwischenfunkt, sondern der PC bis zum Abschluss der Arbeiten seine manuell gesetzte feste IPv4-Adresse behält:
sudo ifconfig eth0 192.168.2.100 netmask 255.255.255.0

**Comment by majuss** [comment]
Super danke für die Hinweise! Ich werde das mal einpflegen, wird aber ne Weile dauern :)

**Comment by majuss** [comment]
Wird im nächsten commit gefixt.
